$axure.loadCurrentPage({
  "url":"登录.html",
  "generationDate":new Date(1528106952846),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"17f16156196442dc9ebd5f9e87e56e9b",
    "type":"Axure:Page",
    "name":"登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e65e85c7013a43aaadd3e34b654e357b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":80,
              "y":20},
            "size":{
              "width":650,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6b868e5bc494a7cb6492386df0c80a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":80,
                  "y":20},
                "size":{
                  "width":650,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/regen/u0.png"}},
{
          "id":"500fc06fa3c94a0bb87c7fe01a39fab9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":309,
              "y":335},
            "size":{
              "width":100,
              "height":35}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 菜单页面",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"ec5508f77ac640a2b24a50e38720e7d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":260,
              "y":200},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05d7b2e141354dc7bc83adc2776022ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":260,
                  "y":200},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3eadb309c6448bb987638e11ca43cd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":260,
              "y":260},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d58e74f880e4d07b0571f9e4cdbed8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":260,
                  "y":260},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b0bf27784e043069b7ca60ae043e8d0",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":339,
              "y":298},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54a044331f804ad69bdcd31dc7a8c237",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":339,
                  "y":298},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"2f1f97fe297c49e5a5b4d5ff4d837f45",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":409,
              "y":298},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e082acf401647a4b54b7017903b483d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":409,
                  "y":298},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"451fcc0de6c444c1bb6dab5297f2ac59",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":429,
              "y":354},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"572de90b8e86453eae300f860d309aa7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":429,
                  "y":354},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"30ed27e7dea14b8986b030ac25a7cf07",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":319,
              "y":200},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"36c9a29cb2e845e4948d22f9b2dbaecd",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":319,
              "y":257},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7bee386988494e05a50f466d19f7a863",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":319,
              "y":132},
            "size":{
              "width":169,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1e04897d25545b1b77011112e31e9bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":319,
                  "y":132},
                "size":{
                  "width":169,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e65e85c7013a43aaadd3e34b654e357b":{
      "scriptId":"u0"},
    "e6b868e5bc494a7cb6492386df0c80a9":{
      "scriptId":"u1"},
    "500fc06fa3c94a0bb87c7fe01a39fab9":{
      "scriptId":"u2"},
    "ec5508f77ac640a2b24a50e38720e7d8":{
      "scriptId":"u3"},
    "05d7b2e141354dc7bc83adc2776022ea":{
      "scriptId":"u4"},
    "f3eadb309c6448bb987638e11ca43cd9":{
      "scriptId":"u5"},
    "5d58e74f880e4d07b0571f9e4cdbed8b":{
      "scriptId":"u6"},
    "4b0bf27784e043069b7ca60ae043e8d0":{
      "scriptId":"u7"},
    "54a044331f804ad69bdcd31dc7a8c237":{
      "scriptId":"u8"},
    "2f1f97fe297c49e5a5b4d5ff4d837f45":{
      "scriptId":"u9"},
    "6e082acf401647a4b54b7017903b483d":{
      "scriptId":"u10"},
    "451fcc0de6c444c1bb6dab5297f2ac59":{
      "scriptId":"u11"},
    "572de90b8e86453eae300f860d309aa7":{
      "scriptId":"u12"},
    "30ed27e7dea14b8986b030ac25a7cf07":{
      "scriptId":"u13"},
    "36c9a29cb2e845e4948d22f9b2dbaecd":{
      "scriptId":"u14"},
    "7bee386988494e05a50f466d19f7a863":{
      "scriptId":"u15"},
    "b1e04897d25545b1b77011112e31e9bd":{
      "scriptId":"u16"}}});