$axure.loadCurrentPage({
  "url":"修改用户信息.html",
  "generationDate":new Date(1528106933949.22),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1945e778ed7f4cc9ba5f90840dba3377",
    "type":"Axure:Page",
    "name":"修改用户信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d3055df53f5a4fa4bd5a871e5f010386",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":120},
            "size":{
              "width":145,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65f876c8e832438d9bc541e255ee25eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":120},
                "size":{
                  "width":145,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19866c90974242d5b8032a99c52ec95c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":262,
              "y":269},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f52a63c531c4989bf7ea0da18561ae1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":262,
                  "y":269},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c485f7fea2e84b368cb23d8dc9467435",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":226,
              "y":208},
            "size":{
              "width":85,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e57273cf5e434e83838782424719a9da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":226,
                  "y":208},
                "size":{
                  "width":85,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ebd56d8b94ec42648f5253918a65be92",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":340,
              "y":208},
            "size":{
              "width":109,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"375d24b842de43cc89033af17ec7f153",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":340,
                  "y":208},
                "size":{
                  "width":109,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6d9e05e9e054092860db4be57f9ea58",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":357,
              "y":269},
            "size":{
              "width":112,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ee0e65b009943fa89a3fb68d88b3878",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":357,
                  "y":269},
                "size":{
                  "width":112,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10fd7d0c2a054f5c982165ae67afa408",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":262,
              "y":328},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db3fdf7da592462da1d541d731f923f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":262,
                  "y":328},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"caa277ed636b42f0a056fb2dff48e71a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":340,
              "y":328},
            "size":{
              "width":97,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5b47e6e3fd240b29c0bf2000c5c8555",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":340,
                  "y":328},
                "size":{
                  "width":97,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38aaec41eab147679a9e8ccde973f9cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":198,
              "y":379},
            "size":{
              "width":113,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e3d1824625a4b59811de6c5ab3bb6a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":198,
                  "y":379},
                "size":{
                  "width":113,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37e0b336eab5451fb3be8db65ef8e48c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":379},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8f8f5bb188ac45b28e3c6891e4dfa316",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":443},
            "size":{
              "width":77,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 重新加载",
                      "target":{
                        "targetType":"reloadPage",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"48c251e636b440cab81145b761b893ae",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":439,
              "y":443},
            "size":{
              "width":77,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 菜单页面",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"8c4dfae29785432c826956ea4cfa2bfd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":50,
              "y":10},
            "size":{
              "width":650,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"950c31a2dded4f9d98fe39970c1f79eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":50,
                  "y":10},
                "size":{
                  "width":650,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改用户信息/regen/u19.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d3055df53f5a4fa4bd5a871e5f010386":{
      "scriptId":"u0"},
    "65f876c8e832438d9bc541e255ee25eb":{
      "scriptId":"u1"},
    "19866c90974242d5b8032a99c52ec95c":{
      "scriptId":"u2"},
    "6f52a63c531c4989bf7ea0da18561ae1":{
      "scriptId":"u3"},
    "c485f7fea2e84b368cb23d8dc9467435":{
      "scriptId":"u4"},
    "e57273cf5e434e83838782424719a9da":{
      "scriptId":"u5"},
    "ebd56d8b94ec42648f5253918a65be92":{
      "scriptId":"u6"},
    "375d24b842de43cc89033af17ec7f153":{
      "scriptId":"u7"},
    "b6d9e05e9e054092860db4be57f9ea58":{
      "scriptId":"u8"},
    "0ee0e65b009943fa89a3fb68d88b3878":{
      "scriptId":"u9"},
    "10fd7d0c2a054f5c982165ae67afa408":{
      "scriptId":"u10"},
    "db3fdf7da592462da1d541d731f923f7":{
      "scriptId":"u11"},
    "caa277ed636b42f0a056fb2dff48e71a":{
      "scriptId":"u12"},
    "d5b47e6e3fd240b29c0bf2000c5c8555":{
      "scriptId":"u13"},
    "38aaec41eab147679a9e8ccde973f9cc":{
      "scriptId":"u14"},
    "7e3d1824625a4b59811de6c5ab3bb6a8":{
      "scriptId":"u15"},
    "37e0b336eab5451fb3be8db65ef8e48c":{
      "scriptId":"u16"},
    "8f8f5bb188ac45b28e3c6891e4dfa316":{
      "scriptId":"u17"},
    "48c251e636b440cab81145b761b893ae":{
      "scriptId":"u18"},
    "8c4dfae29785432c826956ea4cfa2bfd":{
      "scriptId":"u19"},
    "950c31a2dded4f9d98fe39970c1f79eb":{
      "scriptId":"u20"}}});