$axure.loadCurrentPage({
  "url":"查看用户信息.html",
  "generationDate":new Date(1528106939692.67),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"40d233617a8c4734ab59a524acc05ce5",
    "type":"Axure:Page",
    "name":"查看用户信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"25f97c64aa0c4b29b27c3ca0e471b922",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":411,
              "y":119},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e06f850fbd44eb89e2f27e2dc6e05e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":411,
                  "y":119},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1bea104a9e0f4d6089c03891cd3e6bbc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":148,
              "y":201},
            "size":{
              "width":85,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8c53b60de8a44fea33301b78457de78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":148,
                  "y":201},
                "size":{
                  "width":85,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86c83057ae024ba0b855bc129e4ffc7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":197},
            "size":{
              "width":190,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91b39bd034d94513a5567aef8c55989a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":238,
                  "y":197},
                "size":{
                  "width":190,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看用户信息/regen/u4.png"}},
{
          "id":"e99c72ec307c4776a90fbc3de23031ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":184,
              "y":251},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71336060199f4c18bc3bebb8df11758d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":184,
                  "y":251},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"537e06f4ebed4d0aaaaf245802b31087",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":470,
              "y":196},
            "size":{
              "width":85,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a42476c0123c4979ace50abdda832d2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":470,
                  "y":196},
                "size":{
                  "width":85,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8271658ce6e6405ead6836c07790947f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":458,
              "y":262},
            "size":{
              "width":97,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a9b8ee15b9f4909a1b4a7e9af569301",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":458,
                  "y":262},
                "size":{
                  "width":97,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7916ac1405de467a9a88066c3eb91eb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":474,
              "y":316},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00d0b7fb916a4e548c9b742264d3e6d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":474,
                  "y":316},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88dea7ae676748e9a28ae6b8c23c4027",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":184,
              "y":311},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98d8176fd57f4f3dbc5f7a5c9e388cd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":184,
                  "y":311},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b333b496b3444b2f970921051aabe28b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":251},
            "size":{
              "width":190,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f2ce0daee7d49d3a74130ff0d2c807e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":238,
                  "y":251},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看用户信息/regen/u16.png"}},
{
          "id":"b9ccae5cc61f4e1490fa11ca9b415c04",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":311},
            "size":{
              "width":190,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54c696b8007443b38323be49cc3a76ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":238,
                  "y":311},
                "size":{
                  "width":190,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看用户信息/regen/u18.png"}},
{
          "id":"fb9c4b620099488ba0429716d69c994b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":196},
            "size":{
              "width":190,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d86e254c27b846ab8dfd686834e997d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":196},
                "size":{
                  "width":190,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看用户信息/regen/u18.png"}},
{
          "id":"6f05ed28dce34882a855cf297a018d52",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":251},
            "size":{
              "width":190,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8573dd5f09046578b1a6d9682cc055e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":251},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看用户信息/regen/u16.png"}},
{
          "id":"7d8aac01ab7b426c8b47d2745991e60f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":310},
            "size":{
              "width":190,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81c711fe8dbd4de98bed02a68cc17229",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":310},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看用户信息/regen/u16.png"}},
{
          "id":"f1a401f859624f7189c7073294a92bdb",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":673,
              "y":390},
            "size":{
              "width":77,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 菜单页面",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"55887aaeaf0c421ba7ed7c37c11a1540",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":134.5,
              "y":20},
            "size":{
              "width":650,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b51d4f96e6f4df0b3a20d1752e2a10a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":134.5,
                  "y":20},
                "size":{
                  "width":650,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看用户信息/regen/u27.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "25f97c64aa0c4b29b27c3ca0e471b922":{
      "scriptId":"u0"},
    "8e06f850fbd44eb89e2f27e2dc6e05e7":{
      "scriptId":"u1"},
    "1bea104a9e0f4d6089c03891cd3e6bbc":{
      "scriptId":"u2"},
    "a8c53b60de8a44fea33301b78457de78":{
      "scriptId":"u3"},
    "86c83057ae024ba0b855bc129e4ffc7d":{
      "scriptId":"u4"},
    "91b39bd034d94513a5567aef8c55989a":{
      "scriptId":"u5"},
    "e99c72ec307c4776a90fbc3de23031ff":{
      "scriptId":"u6"},
    "71336060199f4c18bc3bebb8df11758d":{
      "scriptId":"u7"},
    "537e06f4ebed4d0aaaaf245802b31087":{
      "scriptId":"u8"},
    "a42476c0123c4979ace50abdda832d2b":{
      "scriptId":"u9"},
    "8271658ce6e6405ead6836c07790947f":{
      "scriptId":"u10"},
    "0a9b8ee15b9f4909a1b4a7e9af569301":{
      "scriptId":"u11"},
    "7916ac1405de467a9a88066c3eb91eb0":{
      "scriptId":"u12"},
    "00d0b7fb916a4e548c9b742264d3e6d0":{
      "scriptId":"u13"},
    "88dea7ae676748e9a28ae6b8c23c4027":{
      "scriptId":"u14"},
    "98d8176fd57f4f3dbc5f7a5c9e388cd6":{
      "scriptId":"u15"},
    "b333b496b3444b2f970921051aabe28b":{
      "scriptId":"u16"},
    "6f2ce0daee7d49d3a74130ff0d2c807e":{
      "scriptId":"u17"},
    "b9ccae5cc61f4e1490fa11ca9b415c04":{
      "scriptId":"u18"},
    "54c696b8007443b38323be49cc3a76ac":{
      "scriptId":"u19"},
    "fb9c4b620099488ba0429716d69c994b":{
      "scriptId":"u20"},
    "d86e254c27b846ab8dfd686834e997d3":{
      "scriptId":"u21"},
    "6f05ed28dce34882a855cf297a018d52":{
      "scriptId":"u22"},
    "a8573dd5f09046578b1a6d9682cc055e":{
      "scriptId":"u23"},
    "7d8aac01ab7b426c8b47d2745991e60f":{
      "scriptId":"u24"},
    "81c711fe8dbd4de98bed02a68cc17229":{
      "scriptId":"u25"},
    "f1a401f859624f7189c7073294a92bdb":{
      "scriptId":"u26"},
    "55887aaeaf0c421ba7ed7c37c11a1540":{
      "scriptId":"u27"},
    "4b51d4f96e6f4df0b3a20d1752e2a10a":{
      "scriptId":"u28"}}});