$axure.loadCurrentPage({
  "url":"课程列表2.html",
  "generationDate":new Date(1528106848763.99),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"23ebd4c6b87044ada1db402136d3d786",
    "type":"Axure:Page",
    "name":"课程列表2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"235e26a9e5be42f197bcfd201cbb54ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":345,
              "y":120},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"faacfa04f05042e79478f5270f8c4608",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":345,
                  "y":120},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18dc1dd887964c97ac65194121537b9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":60,
              "y":130},
            "size":{
              "width":145,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d35937c25e064e729f1a0368038306ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":60,
                  "y":130},
                "size":{
                  "width":145,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课程列表2/regen/u2.png"}},
{
          "id":"eaa1f702aab64795a2162979706f3ff7",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":109,
              "y":164},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSelectionChange":{
              "description":"OnSelectionChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课程列表",
                      "target":{
                        "targetType":"page",
                        "url":"课程列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}}},
{
          "id":"d6a7d8ebc18440f6af3797c99b583c31",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":60,
              "y":164},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c61ebd72822400589d9d1ae6cda7727",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":60,
                  "y":164},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39854f3b913d40ea8d07649572f8abaf",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":240},
            "size":{
              "width":650,
              "height":691}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"269c7ee4553c4e05b80944198be73f26",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":142,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1baadadb81cb48d19cc1632ecba92c09",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":142,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表2/regen/u8.png"}},
{
              "id":"0aad87ba45bb4bc28d94443c09a5957f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":142,
                  "height":163}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"95f5bb8d23284715bd501f00c0ca53ed",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":142,
                      "height":163}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表2/regen/u16.png"}},
{
              "id":"c897d03e0e554d67b920426ec9313985",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":193},
                "size":{
                  "width":142,
                  "height":154}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b1349142b55f4b76aa39ed7ad0c922d7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":193},
                    "size":{
                      "width":142,
                      "height":154}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表2/regen/u24.png"}},
{
              "id":"4ca956179d9a4b4399b57e51155eb38f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":142,
                  "y":0},
                "size":{
                  "width":184,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ecdd6d0c0acd4dc4a5bcb4cfed19739e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":142,
                      "y":0},
                    "size":{
                      "width":184,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表2/regen/u10.png"}},
{
              "id":"f743a6915ec24b6da54c8bf8a421eb27",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":142,
                  "y":30},
                "size":{
                  "width":184,
                  "height":163}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5f70676003b84b2db23eed2fc14d2213",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":142,
                      "y":30},
                    "size":{
                      "width":184,
                      "height":163}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表2/regen/u18.png"}},
{
              "id":"497193a51ccb46649d848638e987ccc8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":142,
                  "y":193},
                "size":{
                  "width":184,
                  "height":154}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"40ec7a23cc57463796db74797c1bae5b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":142,
                      "y":193},
                    "size":{
                      "width":184,
                      "height":154}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表2/regen/u26.png"}},
{
              "id":"f4e9240609bc43079ab10dc622c80756",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":326,
                  "y":0},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fe94dbdf21b54baa8a09c21d53319f9d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":326,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表2/regen/u12.png"}},
{
              "id":"b193ac8c5b8a4e3288c287ea1fa6fc13",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":326,
                  "y":30},
                "size":{
                  "width":150,
                  "height":163}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9da6bd19de2c4c4d95bfa66f3e24cf1e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":326,
                      "y":30},
                    "size":{
                      "width":150,
                      "height":163}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表2/regen/u20.png"}},
{
              "id":"3258e95b16a940198e8e0b9c2a505edd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":326,
                  "y":193},
                "size":{
                  "width":150,
                  "height":154}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fd1c3c64c40340b5b5711200d03a43d5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":326,
                      "y":193},
                    "size":{
                      "width":150,
                      "height":154}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表2/regen/u28.png"}},
{
              "id":"38971aa195724971b9d69b230d1e3815",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":476,
                  "y":0},
                "size":{
                  "width":174,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9701c1d874294df796e36b4e6e0e00e3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":476,
                      "y":0},
                    "size":{
                      "width":174,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表2/regen/u14.png"}},
{
              "id":"929a912388cc4462a5b84b8350e8ee13",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":476,
                  "y":30},
                "size":{
                  "width":174,
                  "height":163}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0f5ad5f3b4024486b92fa638022445f0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":476,
                      "y":30},
                    "size":{
                      "width":174,
                      "height":163}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表2/regen/u22.png"}},
{
              "id":"874a5f755e524baa870126c7b93b07df",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":476,
                  "y":193},
                "size":{
                  "width":174,
                  "height":154}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e5450501f1334b1788b910fe308aeeae",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":476,
                      "y":193},
                    "size":{
                      "width":174,
                      "height":154}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表2/regen/u30.png"}},
{
              "id":"88ab9f9f98894e78adb5e224ce34b281",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":347},
                "size":{
                  "width":142,
                  "height":174}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4579d0ef76f5490ea41e117ee7c60557",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":347},
                    "size":{
                      "width":142,
                      "height":174}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表2/regen/u32.png"}},
{
              "id":"c66fdfbee35947dc93ec094b5db49b85",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":142,
                  "y":347},
                "size":{
                  "width":184,
                  "height":174}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c8e5d22aca9748deaf3c5ae1db6bd8e2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":142,
                      "y":347},
                    "size":{
                      "width":184,
                      "height":174}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表2/regen/u34.png"}},
{
              "id":"8205e07cb3e14f25a5eb94f7457a4dbd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":326,
                  "y":347},
                "size":{
                  "width":150,
                  "height":174}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7b1a947dea4b4c2f8297bdc3a1d222f6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":326,
                      "y":347},
                    "size":{
                      "width":150,
                      "height":174}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表2/regen/u36.png"}},
{
              "id":"0808370f155141aabe60f44d55564c62",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":476,
                  "y":347},
                "size":{
                  "width":174,
                  "height":174}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4ea9608e143c4912ae4198b1819ea18e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":476,
                      "y":347},
                    "size":{
                      "width":174,
                      "height":174}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表2/regen/u38.png"}},
{
              "id":"a8357e8785414db1a44dcfc0ba59e2e9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":521},
                "size":{
                  "width":142,
                  "height":170}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"49f200315c1d488d805cdecfbcd22e3b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":521},
                    "size":{
                      "width":142,
                      "height":170}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表2/regen/u40.png"}},
{
              "id":"5f337d5d67814d28b531d57f17e60a66",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":142,
                  "y":521},
                "size":{
                  "width":184,
                  "height":170}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9e0b081dcbea4396a6e820b9c75b8ac8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":142,
                      "y":521},
                    "size":{
                      "width":184,
                      "height":170}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表2/regen/u42.png"}},
{
              "id":"3e7272539b834555a6742a51c060e035",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":326,
                  "y":521},
                "size":{
                  "width":150,
                  "height":170}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"05d2d0a516d54eb8b3597ec22bc6a5fe",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":326,
                      "y":521},
                    "size":{
                      "width":150,
                      "height":170}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表2/regen/u44.png"}},
{
              "id":"6e4bd407ea2543a7a1e487efeb32fa7e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":476,
                  "y":521},
                "size":{
                  "width":174,
                  "height":170}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4171d4d0aa0f4a66baff6ada163c09f8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":476,
                      "y":521},
                    "size":{
                      "width":174,
                      "height":170}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表2/regen/u46.png"}}]},
{
          "id":"46890627db3e4a75b387d964df3c5225",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":164},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c7de83f5c577486a8e8757fdfd4d7b22",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":461,
              "y":164},
            "size":{
              "width":49,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a38baab8c9574dcc8d3e35e0f9166332",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":461,
                  "y":164},
                "size":{
                  "width":49,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3ca0263333c46d2928858306bc03645",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":418,
              "y":990},
            "size":{
              "width":84,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 菜单页面",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"7d7a3291efbd4036bd35b4447b004772",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":220,
              "y":990},
            "size":{
              "width":84,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课程列表1",
                      "target":{
                        "targetType":"page",
                        "url":"课程列表1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"98b82328baf34d1db88d76cccf730642",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":60,
              "y":10},
            "size":{
              "width":650,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a14c8d0bb50e4c1d83d2fc959dfed2af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":60,
                  "y":10},
                "size":{
                  "width":650,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课程列表2/regen/u53.png"}},
{
          "id":"c5e9d19ce6514758b64e5b05b1b85787",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":565,
              "y":280},
            "size":{
              "width":129,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76d8a1e21eeb461c855d38ffdfc61fc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":565,
                  "y":280},
                "size":{
                  "width":129,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课程列表2/regen/u55.png"}},
{
          "id":"b58403c21963480f8a5db2730f7bdf9a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":440},
            "size":{
              "width":100,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d3d6f25dd09433e88c7ae311a2b242c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":440},
                "size":{
                  "width":100,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课程列表2/regen/u57.png"}},
{
          "id":"865cb164836345f4b273cf23f2325167",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":600},
            "size":{
              "width":110,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"124980802e9149b39f3918d585fb8989",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":570,
                  "y":600},
                "size":{
                  "width":110,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课程列表2/regen/u59.png"}},
{
          "id":"b117e0a233a845b7a0292d6ccb05726a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":547,
              "y":771},
            "size":{
              "width":156,
              "height":149}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab24836cde7f4c1da5c2147acb8c4371",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":547,
                  "y":771},
                "size":{
                  "width":156,
                  "height":149}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课程列表2/regen/u61.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "235e26a9e5be42f197bcfd201cbb54ba":{
      "scriptId":"u0"},
    "faacfa04f05042e79478f5270f8c4608":{
      "scriptId":"u1"},
    "18dc1dd887964c97ac65194121537b9a":{
      "scriptId":"u2"},
    "d35937c25e064e729f1a0368038306ea":{
      "scriptId":"u3"},
    "eaa1f702aab64795a2162979706f3ff7":{
      "scriptId":"u4"},
    "d6a7d8ebc18440f6af3797c99b583c31":{
      "scriptId":"u5"},
    "1c61ebd72822400589d9d1ae6cda7727":{
      "scriptId":"u6"},
    "39854f3b913d40ea8d07649572f8abaf":{
      "scriptId":"u7"},
    "269c7ee4553c4e05b80944198be73f26":{
      "scriptId":"u8"},
    "1baadadb81cb48d19cc1632ecba92c09":{
      "scriptId":"u9"},
    "4ca956179d9a4b4399b57e51155eb38f":{
      "scriptId":"u10"},
    "ecdd6d0c0acd4dc4a5bcb4cfed19739e":{
      "scriptId":"u11"},
    "f4e9240609bc43079ab10dc622c80756":{
      "scriptId":"u12"},
    "fe94dbdf21b54baa8a09c21d53319f9d":{
      "scriptId":"u13"},
    "38971aa195724971b9d69b230d1e3815":{
      "scriptId":"u14"},
    "9701c1d874294df796e36b4e6e0e00e3":{
      "scriptId":"u15"},
    "0aad87ba45bb4bc28d94443c09a5957f":{
      "scriptId":"u16"},
    "95f5bb8d23284715bd501f00c0ca53ed":{
      "scriptId":"u17"},
    "f743a6915ec24b6da54c8bf8a421eb27":{
      "scriptId":"u18"},
    "5f70676003b84b2db23eed2fc14d2213":{
      "scriptId":"u19"},
    "b193ac8c5b8a4e3288c287ea1fa6fc13":{
      "scriptId":"u20"},
    "9da6bd19de2c4c4d95bfa66f3e24cf1e":{
      "scriptId":"u21"},
    "929a912388cc4462a5b84b8350e8ee13":{
      "scriptId":"u22"},
    "0f5ad5f3b4024486b92fa638022445f0":{
      "scriptId":"u23"},
    "c897d03e0e554d67b920426ec9313985":{
      "scriptId":"u24"},
    "b1349142b55f4b76aa39ed7ad0c922d7":{
      "scriptId":"u25"},
    "497193a51ccb46649d848638e987ccc8":{
      "scriptId":"u26"},
    "40ec7a23cc57463796db74797c1bae5b":{
      "scriptId":"u27"},
    "3258e95b16a940198e8e0b9c2a505edd":{
      "scriptId":"u28"},
    "fd1c3c64c40340b5b5711200d03a43d5":{
      "scriptId":"u29"},
    "874a5f755e524baa870126c7b93b07df":{
      "scriptId":"u30"},
    "e5450501f1334b1788b910fe308aeeae":{
      "scriptId":"u31"},
    "88ab9f9f98894e78adb5e224ce34b281":{
      "scriptId":"u32"},
    "4579d0ef76f5490ea41e117ee7c60557":{
      "scriptId":"u33"},
    "c66fdfbee35947dc93ec094b5db49b85":{
      "scriptId":"u34"},
    "c8e5d22aca9748deaf3c5ae1db6bd8e2":{
      "scriptId":"u35"},
    "8205e07cb3e14f25a5eb94f7457a4dbd":{
      "scriptId":"u36"},
    "7b1a947dea4b4c2f8297bdc3a1d222f6":{
      "scriptId":"u37"},
    "0808370f155141aabe60f44d55564c62":{
      "scriptId":"u38"},
    "4ea9608e143c4912ae4198b1819ea18e":{
      "scriptId":"u39"},
    "a8357e8785414db1a44dcfc0ba59e2e9":{
      "scriptId":"u40"},
    "49f200315c1d488d805cdecfbcd22e3b":{
      "scriptId":"u41"},
    "5f337d5d67814d28b531d57f17e60a66":{
      "scriptId":"u42"},
    "9e0b081dcbea4396a6e820b9c75b8ac8":{
      "scriptId":"u43"},
    "3e7272539b834555a6742a51c060e035":{
      "scriptId":"u44"},
    "05d2d0a516d54eb8b3597ec22bc6a5fe":{
      "scriptId":"u45"},
    "6e4bd407ea2543a7a1e487efeb32fa7e":{
      "scriptId":"u46"},
    "4171d4d0aa0f4a66baff6ada163c09f8":{
      "scriptId":"u47"},
    "46890627db3e4a75b387d964df3c5225":{
      "scriptId":"u48"},
    "c7de83f5c577486a8e8757fdfd4d7b22":{
      "scriptId":"u49"},
    "a38baab8c9574dcc8d3e35e0f9166332":{
      "scriptId":"u50"},
    "a3ca0263333c46d2928858306bc03645":{
      "scriptId":"u51"},
    "7d7a3291efbd4036bd35b4447b004772":{
      "scriptId":"u52"},
    "98b82328baf34d1db88d76cccf730642":{
      "scriptId":"u53"},
    "a14c8d0bb50e4c1d83d2fc959dfed2af":{
      "scriptId":"u54"},
    "c5e9d19ce6514758b64e5b05b1b85787":{
      "scriptId":"u55"},
    "76d8a1e21eeb461c855d38ffdfc61fc8":{
      "scriptId":"u56"},
    "b58403c21963480f8a5db2730f7bdf9a":{
      "scriptId":"u57"},
    "8d3d6f25dd09433e88c7ae311a2b242c":{
      "scriptId":"u58"},
    "865cb164836345f4b273cf23f2325167":{
      "scriptId":"u59"},
    "124980802e9149b39f3918d585fb8989":{
      "scriptId":"u60"},
    "b117e0a233a845b7a0292d6ccb05726a":{
      "scriptId":"u61"},
    "ab24836cde7f4c1da5c2147acb8c4371":{
      "scriptId":"u62"}}});