$axure.loadCurrentPage({
  "url":"评定成绩.html",
  "generationDate":new Date(1528106898039.43),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"60264c4e11704971949f91aaeec5fead",
    "type":"Axure:Page",
    "name":"评定成绩",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7d8e4a4e406e4ff2b3610f777859e6a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":374,
              "y":110},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5063799de084481fa24e02f2d94e0dd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":374,
                  "y":110},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9cfe60aedc2040018ac44eacb0f842ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":90,
              "y":161},
            "size":{
              "width":105,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"828b7e69995f4002b9e75cb01d78f169",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":90,
                  "y":161},
                "size":{
                  "width":105,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评定成绩/regen/u2.png"}},
{
          "id":"d2d0476fbfa340f5a9d06ebbae6eb41d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":166},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"7cec395588864e3298de6dcd3d57bd19",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":459,
              "y":166},
            "size":{
              "width":81,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b45def9ccee543d8877c5f7c163379b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":459,
                  "y":166},
                "size":{
                  "width":81,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6125554fc1ae424b9a8896136387928b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":90,
              "y":217},
            "size":{
              "width":330,
              "height":40},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbb0dfcb00f64c80bde224f3d20fb0f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":90,
                  "y":217},
                "size":{
                  "width":330,
                  "height":40},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评定成绩/regen/u7.png"}},
{
          "id":"00d9dfb62c7c4612bf381d66cd16ba25",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":430,
              "y":217},
            "size":{
              "width":170,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f4cb0a0a2c2469ca04b69049f8528f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":430,
                  "y":217},
                "size":{
                  "width":170,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评定成绩/regen/u9.png"}},
{
          "id":"927a5da7afa34a4f83a12860c72bb350",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":90,
              "y":10},
            "size":{
              "width":650,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5387d415421e48db9c5be3a7d82e4414",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":90,
                  "y":10},
                "size":{
                  "width":650,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评定成绩/regen/u11.png"}},
{
          "id":"7bfca5b0658b457d8e13a960352b3192",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":302},
            "size":{
              "width":650,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"142969ac65f94b8e9fcd4364cd5e7a3f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":325,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cc68a3fd7f644e28a219d7ed2172e8ef",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":325,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/评定成绩/regen/u14.png"}},
{
              "id":"ec3772b366b2406aab60c2c3833ad5a3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":325,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a68ba4e20fd541df9c189618b86f4df7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":325,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/评定成绩/regen/u14.png"}},
{
              "id":"d437e1dfe06449fb89f29d480e9dee54",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":325,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1a98d9fceabc4b479a9177e11c3262bd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":325,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/评定成绩/regen/u14.png"}},
{
              "id":"11351b1bf314411fb0f540424f9813cb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":325,
                  "y":0},
                "size":{
                  "width":325,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"60faa94ccb5b4542a02a6cddcb5dda6e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":325,
                      "y":0},
                    "size":{
                      "width":325,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/评定成绩/regen/u16.png"}},
{
              "id":"f114d87c9af942c0a147cf57327a4d3c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000099,
                  "opacity":1},
                "location":{
                  "x":325,
                  "y":30},
                "size":{
                  "width":325,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6b885e19b696451ab69e8790da3e4f85",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000099,
                      "opacity":1},
                    "location":{
                      "x":325,
                      "y":30},
                    "size":{
                      "width":325,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 test1",
                          "target":{
                            "targetType":"page",
                            "url":"test1.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/评定成绩/regen/u16.png"}},
{
              "id":"956ea5e8d7e246c0b65f0732a2e762dc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000099,
                  "opacity":1},
                "location":{
                  "x":325,
                  "y":60},
                "size":{
                  "width":325,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5fdce267dd044fc795426e0575080bec",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000099,
                      "opacity":1},
                    "location":{
                      "x":325,
                      "y":60},
                    "size":{
                      "width":325,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 test2",
                          "target":{
                            "targetType":"page",
                            "url":"test2.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/评定成绩/regen/u16.png"}},
{
              "id":"5e630b75550d4327b17dc7e7dc8c8434",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":325,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"43498df4ca85464bb67a0fadafe20b84",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":325,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/评定成绩/regen/u30.png"}},
{
              "id":"27ff742b15b24fb08778bed26e01c50f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":325,
                  "y":120},
                "size":{
                  "width":325,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9314db7919104f279648b8f109492f0a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":325,
                      "y":120},
                    "size":{
                      "width":325,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/评定成绩/regen/u32.png"}},
{
              "id":"2aa5bac6ca014bf6977badd002992cba",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":325,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3b4d5fe0861c4b7797c26c399a034b3d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":325,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/评定成绩/regen/u14.png"}},
{
              "id":"180ff44f714a46b1ab8a66f33ad7a868",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":325,
                  "y":90},
                "size":{
                  "width":325,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9f6d6a0b69ed421184635079d7d40a73",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":325,
                      "y":90},
                    "size":{
                      "width":325,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/评定成绩/regen/u16.png"}}]},
{
          "id":"e6a3b85a9ba94a47a615ffd416f3bb50",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":660,
              "y":490},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 菜单页面",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"1e2bc503943d4c829b91ab7d33ccf927",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":267},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7ded1e2e76af4a2fa15c8fd3f9927687",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":267},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "7d8e4a4e406e4ff2b3610f777859e6a3":{
      "scriptId":"u0"},
    "5063799de084481fa24e02f2d94e0dd0":{
      "scriptId":"u1"},
    "9cfe60aedc2040018ac44eacb0f842ef":{
      "scriptId":"u2"},
    "828b7e69995f4002b9e75cb01d78f169":{
      "scriptId":"u3"},
    "d2d0476fbfa340f5a9d06ebbae6eb41d":{
      "scriptId":"u4"},
    "7cec395588864e3298de6dcd3d57bd19":{
      "scriptId":"u5"},
    "b45def9ccee543d8877c5f7c163379b3":{
      "scriptId":"u6"},
    "6125554fc1ae424b9a8896136387928b":{
      "scriptId":"u7"},
    "fbb0dfcb00f64c80bde224f3d20fb0f8":{
      "scriptId":"u8"},
    "00d9dfb62c7c4612bf381d66cd16ba25":{
      "scriptId":"u9"},
    "2f4cb0a0a2c2469ca04b69049f8528f6":{
      "scriptId":"u10"},
    "927a5da7afa34a4f83a12860c72bb350":{
      "scriptId":"u11"},
    "5387d415421e48db9c5be3a7d82e4414":{
      "scriptId":"u12"},
    "7bfca5b0658b457d8e13a960352b3192":{
      "scriptId":"u13"},
    "142969ac65f94b8e9fcd4364cd5e7a3f":{
      "scriptId":"u14"},
    "cc68a3fd7f644e28a219d7ed2172e8ef":{
      "scriptId":"u15"},
    "11351b1bf314411fb0f540424f9813cb":{
      "scriptId":"u16"},
    "60faa94ccb5b4542a02a6cddcb5dda6e":{
      "scriptId":"u17"},
    "ec3772b366b2406aab60c2c3833ad5a3":{
      "scriptId":"u18"},
    "a68ba4e20fd541df9c189618b86f4df7":{
      "scriptId":"u19"},
    "f114d87c9af942c0a147cf57327a4d3c":{
      "scriptId":"u20"},
    "6b885e19b696451ab69e8790da3e4f85":{
      "scriptId":"u21"},
    "d437e1dfe06449fb89f29d480e9dee54":{
      "scriptId":"u22"},
    "1a98d9fceabc4b479a9177e11c3262bd":{
      "scriptId":"u23"},
    "956ea5e8d7e246c0b65f0732a2e762dc":{
      "scriptId":"u24"},
    "5fdce267dd044fc795426e0575080bec":{
      "scriptId":"u25"},
    "2aa5bac6ca014bf6977badd002992cba":{
      "scriptId":"u26"},
    "3b4d5fe0861c4b7797c26c399a034b3d":{
      "scriptId":"u27"},
    "180ff44f714a46b1ab8a66f33ad7a868":{
      "scriptId":"u28"},
    "9f6d6a0b69ed421184635079d7d40a73":{
      "scriptId":"u29"},
    "5e630b75550d4327b17dc7e7dc8c8434":{
      "scriptId":"u30"},
    "43498df4ca85464bb67a0fadafe20b84":{
      "scriptId":"u31"},
    "27ff742b15b24fb08778bed26e01c50f":{
      "scriptId":"u32"},
    "9314db7919104f279648b8f109492f0a":{
      "scriptId":"u33"},
    "e6a3b85a9ba94a47a615ffd416f3bb50":{
      "scriptId":"u34"},
    "1e2bc503943d4c829b91ab7d33ccf927":{
      "scriptId":"u35"},
    "7ded1e2e76af4a2fa15c8fd3f9927687":{
      "scriptId":"u36"}}});