$axure.loadCurrentPage({
  "url":"教师选课.html",
  "generationDate":new Date(1528106916023.87),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3b730282c357404387ed480996213821",
    "type":"Axure:Page",
    "name":"教师选课",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"86ef7481d7424d5e8b90076783c44860",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":345,
              "y":120},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acb6328d473142faaa02b9c4bac62634",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":345,
                  "y":120},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07ce14197ef248018a33038b9399fdad",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":60,
              "y":130},
            "size":{
              "width":145,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6afcd64368834e16988c4a48edf9c6b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":60,
                  "y":130},
                "size":{
                  "width":145,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教师选课/regen/u2.png"}},
{
          "id":"d17c2cde714542049e2ec70344daca33",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":109,
              "y":164},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSelectionChange":{
              "description":"OnSelectionChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课程列表1",
                      "target":{
                        "targetType":"page",
                        "url":"课程列表1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}}},
{
          "id":"5a55d16b27a1451180567e93c4c84b09",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":60,
              "y":164},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14f0747662e244fcb786ca9d4d3abff3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":60,
                  "y":164},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"053bb258e5974bfeaef5e2c73cf4eee4",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":240},
            "size":{
              "width":650,
              "height":691}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"006916cd52c24d1c8776513a87a7757d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":142,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"996aebef97fa4846aaf58975e87d554b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":142,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/教师选课/regen/u8.png"}},
{
              "id":"95dc51a96f474cdeb8d67ec46f5af01a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":142,
                  "height":163}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"757229c3a35943078b5bfc55ee1f9a41",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":142,
                      "height":163}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/教师选课/regen/u16.png"}},
{
              "id":"3225738985954ead92ee61e6c5a0b277",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":193},
                "size":{
                  "width":142,
                  "height":154}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"04b1ac7272f447d0ad6609d3b9489f38",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":193},
                    "size":{
                      "width":142,
                      "height":154}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/教师选课/regen/u24.png"}},
{
              "id":"b72eb98d9b2b4e17be8911497f9f7769",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":142,
                  "y":0},
                "size":{
                  "width":184,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"524e97d5c1bf48338f0d47875c5610b2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":142,
                      "y":0},
                    "size":{
                      "width":184,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/教师选课/regen/u10.png"}},
{
              "id":"afbd2b45811c4b16828961ea0c94d5e6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":142,
                  "y":30},
                "size":{
                  "width":184,
                  "height":163}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8dac2ac27244430fac5f426a3725b0b9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":142,
                      "y":30},
                    "size":{
                      "width":184,
                      "height":163}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/教师选课/regen/u18.png"}},
{
              "id":"2765bdb7f91c462a99d792b5d34788d2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":142,
                  "y":193},
                "size":{
                  "width":184,
                  "height":154}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fcdd99634aa5449fa7eed7e39e0570f6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":142,
                      "y":193},
                    "size":{
                      "width":184,
                      "height":154}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/教师选课/regen/u26.png"}},
{
              "id":"7e970716475943c7b44bccb24d199972",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":326,
                  "y":0},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"288c741efff5493b84aca7354e5bfce7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":326,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/教师选课/regen/u12.png"}},
{
              "id":"8a859f764e2d479ea81950fb2324d53d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":326,
                  "y":30},
                "size":{
                  "width":150,
                  "height":163}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"414caefb538648788d86a29dab7f14bf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":326,
                      "y":30},
                    "size":{
                      "width":150,
                      "height":163}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/教师选课/regen/u20.png"}},
{
              "id":"514546bb80dd4df4b2237044bcf182ff",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":326,
                  "y":193},
                "size":{
                  "width":150,
                  "height":154}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d0e370260eb54c13931a34865b767beb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":326,
                      "y":193},
                    "size":{
                      "width":150,
                      "height":154}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/教师选课/regen/u28.png"}},
{
              "id":"91a770d1d400475bbf287ad0d430bd79",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":476,
                  "y":0},
                "size":{
                  "width":174,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8e192caf1f9145fd9e8e5a5e8d7c2a9e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":476,
                      "y":0},
                    "size":{
                      "width":174,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/教师选课/regen/u14.png"}},
{
              "id":"ade687eedced4139a9074eebe2bc7dde",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":476,
                  "y":30},
                "size":{
                  "width":174,
                  "height":163}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d9117f20b27148f08ab04c3d37a90c27",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":476,
                      "y":30},
                    "size":{
                      "width":174,
                      "height":163}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/教师选课/regen/u22.png"}},
{
              "id":"3d214cf9da4e4984b093925fbf9eda19",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":476,
                  "y":193},
                "size":{
                  "width":174,
                  "height":154}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5b7a6a75ac2e41ef9d6199a358be1c2c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":476,
                      "y":193},
                    "size":{
                      "width":174,
                      "height":154}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/教师选课/regen/u30.png"}},
{
              "id":"5cb4b416a721489bb9116d698fc4086f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":347},
                "size":{
                  "width":142,
                  "height":174}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"925fc519236441b88413f8142dacf36f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":347},
                    "size":{
                      "width":142,
                      "height":174}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/教师选课/regen/u32.png"}},
{
              "id":"58e0334b26954a3ca3b9a0f0a781abc9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":142,
                  "y":347},
                "size":{
                  "width":184,
                  "height":174}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7a8358bf29b045f0b591f665fc074ed6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":142,
                      "y":347},
                    "size":{
                      "width":184,
                      "height":174}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/教师选课/regen/u34.png"}},
{
              "id":"7a67f616490f4e67b9480969273d8ac2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":326,
                  "y":347},
                "size":{
                  "width":150,
                  "height":174}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2b8d3ba2800948018146ef48f3875121",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":326,
                      "y":347},
                    "size":{
                      "width":150,
                      "height":174}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/教师选课/regen/u36.png"}},
{
              "id":"8ba8982775484538a6063f56ae4e8ff2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":476,
                  "y":347},
                "size":{
                  "width":174,
                  "height":174}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"68726d833bbe491d964c0333a5adcdfd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":476,
                      "y":347},
                    "size":{
                      "width":174,
                      "height":174}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/教师选课/regen/u38.png"}},
{
              "id":"335485aeee8d414b83270108ee7be136",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":521},
                "size":{
                  "width":142,
                  "height":170}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"34f14f99b98f4f94aee568513ccf6c8e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":521},
                    "size":{
                      "width":142,
                      "height":170}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/教师选课/regen/u40.png"}},
{
              "id":"88b8b076df7c4ed98cb4a169e2afa1d4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":142,
                  "y":521},
                "size":{
                  "width":184,
                  "height":170}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"37aa1783b31846c0829e586ecae325dc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":142,
                      "y":521},
                    "size":{
                      "width":184,
                      "height":170}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/教师选课/regen/u42.png"}},
{
              "id":"4816e951ebbc4d9289b751f483b171e7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":326,
                  "y":521},
                "size":{
                  "width":150,
                  "height":170}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"19f13642df054f7aa09891bca990e034",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":326,
                      "y":521},
                    "size":{
                      "width":150,
                      "height":170}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/教师选课/regen/u44.png"}},
{
              "id":"8a36c4f141864dd59f6b07303a100717",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":476,
                  "y":521},
                "size":{
                  "width":174,
                  "height":170}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4e1dba31841249b3a496138acfe7e23d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":476,
                      "y":521},
                    "size":{
                      "width":174,
                      "height":170}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/教师选课/regen/u46.png"}}]},
{
          "id":"122362ba82694acba61a1cc96cc056c6",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":164},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"50fb601892a046fb9f0fbbf08fcdff5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":461,
              "y":164},
            "size":{
              "width":49,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbd50749f9b84638afa9161a8f503371",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":461,
                  "y":164},
                "size":{
                  "width":49,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d1ffdac1d0424cc2bcaea2d8cda2191d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":418,
              "y":990},
            "size":{
              "width":84,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 菜单页面",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"02f0ce3ed5d94e2bb23e9498846001de",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":551,
              "y":300},
            "size":{
              "width":137,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c21dc90c45c2488da2ec56e22c93090a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":551,
                  "y":300},
                "size":{
                  "width":137,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教师选课/regen/u52.png"}},
{
          "id":"5c040706b6ec4ab49f68b00c8ba15236",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":556,
              "y":452},
            "size":{
              "width":132,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"548d868b776a4a03a1ea89186b0bff9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":556,
                  "y":452},
                "size":{
                  "width":132,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教师选课/regen/u54.png"}},
{
          "id":"3ab4d7d87b5e4238a56d58ed0368ee80",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":600},
            "size":{
              "width":144,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcb4c858eaa644a795b7f57aeda4ab72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":600},
                "size":{
                  "width":144,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教师选课/regen/u56.png"}},
{
          "id":"5e8c8f5992da4bd39eb4ade476cea895",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":565,
              "y":780},
            "size":{
              "width":115,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0053aaa7e5014ac7a8bee6f19f410426",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":565,
                  "y":780},
                "size":{
                  "width":115,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教师选课/regen/u58.png"}},
{
          "id":"dfed2be551e44b3793a0a9d1781c984f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":220,
              "y":990},
            "size":{
              "width":84,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 重新加载",
                      "target":{
                        "targetType":"reloadPage",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"1cb5d9186dcc44a692c6e818bb79efff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":60,
              "y":10},
            "size":{
              "width":650,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cbe67abd4d8474fbd758631c9665218",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":60,
                  "y":10},
                "size":{
                  "width":650,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教师选课/regen/u61.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "86ef7481d7424d5e8b90076783c44860":{
      "scriptId":"u0"},
    "acb6328d473142faaa02b9c4bac62634":{
      "scriptId":"u1"},
    "07ce14197ef248018a33038b9399fdad":{
      "scriptId":"u2"},
    "6afcd64368834e16988c4a48edf9c6b3":{
      "scriptId":"u3"},
    "d17c2cde714542049e2ec70344daca33":{
      "scriptId":"u4"},
    "5a55d16b27a1451180567e93c4c84b09":{
      "scriptId":"u5"},
    "14f0747662e244fcb786ca9d4d3abff3":{
      "scriptId":"u6"},
    "053bb258e5974bfeaef5e2c73cf4eee4":{
      "scriptId":"u7"},
    "006916cd52c24d1c8776513a87a7757d":{
      "scriptId":"u8"},
    "996aebef97fa4846aaf58975e87d554b":{
      "scriptId":"u9"},
    "b72eb98d9b2b4e17be8911497f9f7769":{
      "scriptId":"u10"},
    "524e97d5c1bf48338f0d47875c5610b2":{
      "scriptId":"u11"},
    "7e970716475943c7b44bccb24d199972":{
      "scriptId":"u12"},
    "288c741efff5493b84aca7354e5bfce7":{
      "scriptId":"u13"},
    "91a770d1d400475bbf287ad0d430bd79":{
      "scriptId":"u14"},
    "8e192caf1f9145fd9e8e5a5e8d7c2a9e":{
      "scriptId":"u15"},
    "95dc51a96f474cdeb8d67ec46f5af01a":{
      "scriptId":"u16"},
    "757229c3a35943078b5bfc55ee1f9a41":{
      "scriptId":"u17"},
    "afbd2b45811c4b16828961ea0c94d5e6":{
      "scriptId":"u18"},
    "8dac2ac27244430fac5f426a3725b0b9":{
      "scriptId":"u19"},
    "8a859f764e2d479ea81950fb2324d53d":{
      "scriptId":"u20"},
    "414caefb538648788d86a29dab7f14bf":{
      "scriptId":"u21"},
    "ade687eedced4139a9074eebe2bc7dde":{
      "scriptId":"u22"},
    "d9117f20b27148f08ab04c3d37a90c27":{
      "scriptId":"u23"},
    "3225738985954ead92ee61e6c5a0b277":{
      "scriptId":"u24"},
    "04b1ac7272f447d0ad6609d3b9489f38":{
      "scriptId":"u25"},
    "2765bdb7f91c462a99d792b5d34788d2":{
      "scriptId":"u26"},
    "fcdd99634aa5449fa7eed7e39e0570f6":{
      "scriptId":"u27"},
    "514546bb80dd4df4b2237044bcf182ff":{
      "scriptId":"u28"},
    "d0e370260eb54c13931a34865b767beb":{
      "scriptId":"u29"},
    "3d214cf9da4e4984b093925fbf9eda19":{
      "scriptId":"u30"},
    "5b7a6a75ac2e41ef9d6199a358be1c2c":{
      "scriptId":"u31"},
    "5cb4b416a721489bb9116d698fc4086f":{
      "scriptId":"u32"},
    "925fc519236441b88413f8142dacf36f":{
      "scriptId":"u33"},
    "58e0334b26954a3ca3b9a0f0a781abc9":{
      "scriptId":"u34"},
    "7a8358bf29b045f0b591f665fc074ed6":{
      "scriptId":"u35"},
    "7a67f616490f4e67b9480969273d8ac2":{
      "scriptId":"u36"},
    "2b8d3ba2800948018146ef48f3875121":{
      "scriptId":"u37"},
    "8ba8982775484538a6063f56ae4e8ff2":{
      "scriptId":"u38"},
    "68726d833bbe491d964c0333a5adcdfd":{
      "scriptId":"u39"},
    "335485aeee8d414b83270108ee7be136":{
      "scriptId":"u40"},
    "34f14f99b98f4f94aee568513ccf6c8e":{
      "scriptId":"u41"},
    "88b8b076df7c4ed98cb4a169e2afa1d4":{
      "scriptId":"u42"},
    "37aa1783b31846c0829e586ecae325dc":{
      "scriptId":"u43"},
    "4816e951ebbc4d9289b751f483b171e7":{
      "scriptId":"u44"},
    "19f13642df054f7aa09891bca990e034":{
      "scriptId":"u45"},
    "8a36c4f141864dd59f6b07303a100717":{
      "scriptId":"u46"},
    "4e1dba31841249b3a496138acfe7e23d":{
      "scriptId":"u47"},
    "122362ba82694acba61a1cc96cc056c6":{
      "scriptId":"u48"},
    "50fb601892a046fb9f0fbbf08fcdff5c":{
      "scriptId":"u49"},
    "fbd50749f9b84638afa9161a8f503371":{
      "scriptId":"u50"},
    "d1ffdac1d0424cc2bcaea2d8cda2191d":{
      "scriptId":"u51"},
    "02f0ce3ed5d94e2bb23e9498846001de":{
      "scriptId":"u52"},
    "c21dc90c45c2488da2ec56e22c93090a":{
      "scriptId":"u53"},
    "5c040706b6ec4ab49f68b00c8ba15236":{
      "scriptId":"u54"},
    "548d868b776a4a03a1ea89186b0bff9d":{
      "scriptId":"u55"},
    "3ab4d7d87b5e4238a56d58ed0368ee80":{
      "scriptId":"u56"},
    "bcb4c858eaa644a795b7f57aeda4ab72":{
      "scriptId":"u57"},
    "5e8c8f5992da4bd39eb4ade476cea895":{
      "scriptId":"u58"},
    "0053aaa7e5014ac7a8bee6f19f410426":{
      "scriptId":"u59"},
    "dfed2be551e44b3793a0a9d1781c984f":{
      "scriptId":"u60"},
    "1cb5d9186dcc44a692c6e818bb79efff":{
      "scriptId":"u61"},
    "2cbe67abd4d8474fbd758631c9665218":{
      "scriptId":"u62"}}});