$axure.loadCurrentPage({
  "url":"课程列表1.html",
  "generationDate":new Date(1528106854090.83),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7ade768abd8046dea58557c40304d3a9",
    "type":"Axure:Page",
    "name":"课程列表1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"93fe2e35e3d94e7abc8b44f66731db3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":345,
              "y":120},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3a76fd3f69d4d16b2894428d74f17a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":345,
                  "y":120},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46a53af53cac4d28a9d374e5077ba551",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":60,
              "y":130},
            "size":{
              "width":145,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27ca7624edb94ad795fca9ee06e8652f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":60,
                  "y":130},
                "size":{
                  "width":145,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课程列表1/regen/u2.png"}},
{
          "id":"632a719e6f0f495abdac1abeaa420177",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":109,
              "y":164},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSelectionChange":{
              "description":"OnSelectionChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课程列表",
                      "target":{
                        "targetType":"page",
                        "url":"课程列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}}},
{
          "id":"6663c075cc904ae19859fd03dd39f51f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":60,
              "y":164},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"582b1edde9134965b0e6fa53911ddd79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":60,
                  "y":164},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c695934b85f4e3eb980b675232da84c",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":240},
            "size":{
              "width":650,
              "height":691}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d226efdec53f4b7b8e4ccbb248ed8931",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":142,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5012783842184eb09b3a68f863df47f6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":142,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表1/regen/u8.png"}},
{
              "id":"c352d5ba12074abf96bb8f701716bec7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":142,
                  "height":163}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7590e48f3469405c9cd5d2d8ff02d468",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":142,
                      "height":163}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表1/regen/u16.png"}},
{
              "id":"adcc9ff7e64443dab166964919a09e3b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":193},
                "size":{
                  "width":142,
                  "height":154}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d032f0b261d14cf7a8ae2b71f532145e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":193},
                    "size":{
                      "width":142,
                      "height":154}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表1/regen/u24.png"}},
{
              "id":"5a7682072f9048d5af97ebc0ec0fe2ae",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":142,
                  "y":0},
                "size":{
                  "width":184,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bb6f93a229054bf99670c01356acc37a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":142,
                      "y":0},
                    "size":{
                      "width":184,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表1/regen/u10.png"}},
{
              "id":"e4602f30a52a406cad0512672952717c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":142,
                  "y":30},
                "size":{
                  "width":184,
                  "height":163}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a3df56e3f208421fa70afcbce24b4cba",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":142,
                      "y":30},
                    "size":{
                      "width":184,
                      "height":163}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表1/regen/u18.png"}},
{
              "id":"9f6ce3fa2ccd408ca5686ff312dd7dc9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":142,
                  "y":193},
                "size":{
                  "width":184,
                  "height":154}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fe43ebfbf71d4d6f9a88a75ce3d3aeec",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":142,
                      "y":193},
                    "size":{
                      "width":184,
                      "height":154}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表1/regen/u26.png"}},
{
              "id":"e38e055f070f4cbdb34df86d75613664",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":326,
                  "y":0},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"36d28bdb52fe498ebfe66f61feb065b8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":326,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表1/regen/u12.png"}},
{
              "id":"b25f2944d17a46379a0afca56e1eed71",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":326,
                  "y":30},
                "size":{
                  "width":150,
                  "height":163}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1bb9253b171f43419599d828129cd0c3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":326,
                      "y":30},
                    "size":{
                      "width":150,
                      "height":163}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表1/regen/u20.png"}},
{
              "id":"f4216b7e48ea4fb098bc1b8663fc619c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":326,
                  "y":193},
                "size":{
                  "width":150,
                  "height":154}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fe8bd99e03744ae58b68ec091e02b32e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":326,
                      "y":193},
                    "size":{
                      "width":150,
                      "height":154}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表1/regen/u28.png"}},
{
              "id":"2728132795c94608a092674947a03c20",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":476,
                  "y":0},
                "size":{
                  "width":174,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9a848b807b73434988a1caf9c2722e0f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":476,
                      "y":0},
                    "size":{
                      "width":174,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表1/regen/u14.png"}},
{
              "id":"8212272ca3184163a3e94d769e795ee8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":476,
                  "y":30},
                "size":{
                  "width":174,
                  "height":163}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0178699fb3af4b0598d5dae9f99ef3ba",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":476,
                      "y":30},
                    "size":{
                      "width":174,
                      "height":163}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表1/regen/u22.png"}},
{
              "id":"68351b760c7b4933b78f13d7ae9ef8a8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":476,
                  "y":193},
                "size":{
                  "width":174,
                  "height":154}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2092a58e92984edf80cf177110c2afd1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":476,
                      "y":193},
                    "size":{
                      "width":174,
                      "height":154}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表1/regen/u30.png"}},
{
              "id":"fe40a055717047ec924d1fdff7e910ce",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":347},
                "size":{
                  "width":142,
                  "height":174}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c444accdfe224d2d88e3c4d1e4616f68",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":347},
                    "size":{
                      "width":142,
                      "height":174}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表1/regen/u32.png"}},
{
              "id":"ed1bb953125e48eb8551407cf8d91397",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":142,
                  "y":347},
                "size":{
                  "width":184,
                  "height":174}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9874941a305742938a8ca78958151edc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":142,
                      "y":347},
                    "size":{
                      "width":184,
                      "height":174}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表1/regen/u34.png"}},
{
              "id":"1060fdaf04a64ddf9794ff3f44cc9696",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":326,
                  "y":347},
                "size":{
                  "width":150,
                  "height":174}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2c8865b4d6ff4cdaa7e60cf86505b040",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":326,
                      "y":347},
                    "size":{
                      "width":150,
                      "height":174}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表1/regen/u36.png"}},
{
              "id":"8de50215aa1340d5b43279843231cf53",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":476,
                  "y":347},
                "size":{
                  "width":174,
                  "height":174}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"00a880fba88d411f8f1eadee13cb9925",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":476,
                      "y":347},
                    "size":{
                      "width":174,
                      "height":174}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表1/regen/u38.png"}},
{
              "id":"987ae0c2be4d411d80c166a7f4fdfccf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":521},
                "size":{
                  "width":142,
                  "height":170}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"abab6bfe9eaf4cd38d1cac0d00efc2f7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":521},
                    "size":{
                      "width":142,
                      "height":170}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表1/regen/u40.png"}},
{
              "id":"39148bc2b4b14f0f886113404804cac3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":142,
                  "y":521},
                "size":{
                  "width":184,
                  "height":170}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f7f360b2be90414fa97784d899c539f3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":142,
                      "y":521},
                    "size":{
                      "width":184,
                      "height":170}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表1/regen/u42.png"}},
{
              "id":"cd904b921bc845bca1f7558aec4b4f70",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":326,
                  "y":521},
                "size":{
                  "width":150,
                  "height":170}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"78fc4bf22df4451a905d66046b7e04ec",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":326,
                      "y":521},
                    "size":{
                      "width":150,
                      "height":170}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表1/regen/u44.png"}},
{
              "id":"d0f9d6abf2984961b78c323ef07b8732",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":476,
                  "y":521},
                "size":{
                  "width":174,
                  "height":170}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a711bb953ef84a6b924c8c5337ab7acf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":476,
                      "y":521},
                    "size":{
                      "width":174,
                      "height":170}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表1/regen/u46.png"}}]},
{
          "id":"a4bbca78642d4feeb2c2bf1defca044c",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":164},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"bf070845fdbe4d15982ac99a3e3dc4fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":461,
              "y":164},
            "size":{
              "width":49,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03dc0056160648e5861bd4bf84a0d349",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":461,
                  "y":164},
                "size":{
                  "width":49,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7164d1413fc048919256641c3d0d48c2",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":418,
              "y":990},
            "size":{
              "width":84,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 菜单页面",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e267e53831784ba4b48f81c002d5ee01",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":220,
              "y":990},
            "size":{
              "width":84,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课程列表1",
                      "target":{
                        "targetType":"page",
                        "url":"课程列表1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"6ab0a561516740c3bf8a1339e1aed6ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":60,
              "y":10},
            "size":{
              "width":650,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33bc861b6b4f41f481141ccf8b03157d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":60,
                  "y":10},
                "size":{
                  "width":650,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课程列表1/regen/u53.png"}},
{
          "id":"3aab8bb945b746c28a1767bc3aced29f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":565,
              "y":280},
            "size":{
              "width":129,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b5566a1163e480ca4c54ed3b91d64f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":565,
                  "y":280},
                "size":{
                  "width":129,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课程列表1/regen/u55.png"}},
{
          "id":"81d147e840e94665bd24ceb1f624fffe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":579.5,
              "y":440},
            "size":{
              "width":100,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"565e5cfc68d643f7b61d3abaad0950ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":579.5,
                  "y":440},
                "size":{
                  "width":100,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课程列表1/regen/u57.png"}},
{
          "id":"a2a15066a0bf43a894ae11501304cbe0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":600},
            "size":{
              "width":110,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0ac3a17b08c4da9827745f073d2ebac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":570,
                  "y":600},
                "size":{
                  "width":110,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课程列表1/regen/u59.png"}},
{
          "id":"7d42951c90da43fab44980839aac6c81",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":547,
              "y":771},
            "size":{
              "width":156,
              "height":149}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"121b28c389c54e2980062dbc06ac112c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":547,
                  "y":771},
                "size":{
                  "width":156,
                  "height":149}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课程列表1/regen/u61.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "93fe2e35e3d94e7abc8b44f66731db3b":{
      "scriptId":"u0"},
    "a3a76fd3f69d4d16b2894428d74f17a8":{
      "scriptId":"u1"},
    "46a53af53cac4d28a9d374e5077ba551":{
      "scriptId":"u2"},
    "27ca7624edb94ad795fca9ee06e8652f":{
      "scriptId":"u3"},
    "632a719e6f0f495abdac1abeaa420177":{
      "scriptId":"u4"},
    "6663c075cc904ae19859fd03dd39f51f":{
      "scriptId":"u5"},
    "582b1edde9134965b0e6fa53911ddd79":{
      "scriptId":"u6"},
    "4c695934b85f4e3eb980b675232da84c":{
      "scriptId":"u7"},
    "d226efdec53f4b7b8e4ccbb248ed8931":{
      "scriptId":"u8"},
    "5012783842184eb09b3a68f863df47f6":{
      "scriptId":"u9"},
    "5a7682072f9048d5af97ebc0ec0fe2ae":{
      "scriptId":"u10"},
    "bb6f93a229054bf99670c01356acc37a":{
      "scriptId":"u11"},
    "e38e055f070f4cbdb34df86d75613664":{
      "scriptId":"u12"},
    "36d28bdb52fe498ebfe66f61feb065b8":{
      "scriptId":"u13"},
    "2728132795c94608a092674947a03c20":{
      "scriptId":"u14"},
    "9a848b807b73434988a1caf9c2722e0f":{
      "scriptId":"u15"},
    "c352d5ba12074abf96bb8f701716bec7":{
      "scriptId":"u16"},
    "7590e48f3469405c9cd5d2d8ff02d468":{
      "scriptId":"u17"},
    "e4602f30a52a406cad0512672952717c":{
      "scriptId":"u18"},
    "a3df56e3f208421fa70afcbce24b4cba":{
      "scriptId":"u19"},
    "b25f2944d17a46379a0afca56e1eed71":{
      "scriptId":"u20"},
    "1bb9253b171f43419599d828129cd0c3":{
      "scriptId":"u21"},
    "8212272ca3184163a3e94d769e795ee8":{
      "scriptId":"u22"},
    "0178699fb3af4b0598d5dae9f99ef3ba":{
      "scriptId":"u23"},
    "adcc9ff7e64443dab166964919a09e3b":{
      "scriptId":"u24"},
    "d032f0b261d14cf7a8ae2b71f532145e":{
      "scriptId":"u25"},
    "9f6ce3fa2ccd408ca5686ff312dd7dc9":{
      "scriptId":"u26"},
    "fe43ebfbf71d4d6f9a88a75ce3d3aeec":{
      "scriptId":"u27"},
    "f4216b7e48ea4fb098bc1b8663fc619c":{
      "scriptId":"u28"},
    "fe8bd99e03744ae58b68ec091e02b32e":{
      "scriptId":"u29"},
    "68351b760c7b4933b78f13d7ae9ef8a8":{
      "scriptId":"u30"},
    "2092a58e92984edf80cf177110c2afd1":{
      "scriptId":"u31"},
    "fe40a055717047ec924d1fdff7e910ce":{
      "scriptId":"u32"},
    "c444accdfe224d2d88e3c4d1e4616f68":{
      "scriptId":"u33"},
    "ed1bb953125e48eb8551407cf8d91397":{
      "scriptId":"u34"},
    "9874941a305742938a8ca78958151edc":{
      "scriptId":"u35"},
    "1060fdaf04a64ddf9794ff3f44cc9696":{
      "scriptId":"u36"},
    "2c8865b4d6ff4cdaa7e60cf86505b040":{
      "scriptId":"u37"},
    "8de50215aa1340d5b43279843231cf53":{
      "scriptId":"u38"},
    "00a880fba88d411f8f1eadee13cb9925":{
      "scriptId":"u39"},
    "987ae0c2be4d411d80c166a7f4fdfccf":{
      "scriptId":"u40"},
    "abab6bfe9eaf4cd38d1cac0d00efc2f7":{
      "scriptId":"u41"},
    "39148bc2b4b14f0f886113404804cac3":{
      "scriptId":"u42"},
    "f7f360b2be90414fa97784d899c539f3":{
      "scriptId":"u43"},
    "cd904b921bc845bca1f7558aec4b4f70":{
      "scriptId":"u44"},
    "78fc4bf22df4451a905d66046b7e04ec":{
      "scriptId":"u45"},
    "d0f9d6abf2984961b78c323ef07b8732":{
      "scriptId":"u46"},
    "a711bb953ef84a6b924c8c5337ab7acf":{
      "scriptId":"u47"},
    "a4bbca78642d4feeb2c2bf1defca044c":{
      "scriptId":"u48"},
    "bf070845fdbe4d15982ac99a3e3dc4fd":{
      "scriptId":"u49"},
    "03dc0056160648e5861bd4bf84a0d349":{
      "scriptId":"u50"},
    "7164d1413fc048919256641c3d0d48c2":{
      "scriptId":"u51"},
    "e267e53831784ba4b48f81c002d5ee01":{
      "scriptId":"u52"},
    "6ab0a561516740c3bf8a1339e1aed6ef":{
      "scriptId":"u53"},
    "33bc861b6b4f41f481141ccf8b03157d":{
      "scriptId":"u54"},
    "3aab8bb945b746c28a1767bc3aced29f":{
      "scriptId":"u55"},
    "0b5566a1163e480ca4c54ed3b91d64f6":{
      "scriptId":"u56"},
    "81d147e840e94665bd24ceb1f624fffe":{
      "scriptId":"u57"},
    "565e5cfc68d643f7b61d3abaad0950ed":{
      "scriptId":"u58"},
    "a2a15066a0bf43a894ae11501304cbe0":{
      "scriptId":"u59"},
    "c0ac3a17b08c4da9827745f073d2ebac":{
      "scriptId":"u60"},
    "7d42951c90da43fab44980839aac6c81":{
      "scriptId":"u61"},
    "121b28c389c54e2980062dbc06ac112c":{
      "scriptId":"u62"}}});