$axure.loadCurrentPage({
  "url":"test1.html",
  "generationDate":new Date(1528106842552.85),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a28840c3aadc4852873b0befc1ef828a",
    "type":"Axure:Page",
    "name":"test1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1dc34aff5816461b9ceb772e26d65b6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":180,
              "y":10},
            "size":{
              "width":650,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab4e1b57bba44f8e9cebe163d0e659e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":180,
                  "y":10},
                "size":{
                  "width":650,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/test1/regen/u0.png"}},
{
          "id":"8faebd7904bb4d4bbe805c82315d165d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":122},
            "size":{
              "width":217,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8935c56731b4613a1e27d0a235985a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":122},
                "size":{
                  "width":217,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4af4b335c7e446c883b7571790ae4e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":414,
              "y":180},
            "size":{
              "width":155,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4f5878d42c94763ace901a6cafbcc8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":414,
                  "y":180},
                "size":{
                  "width":155,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c4a263022bf46e8b256ae0db0697a74",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":230},
            "size":{
              "width":660,
              "height":210}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"829c577e306c4b61be3a07c6960adeca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":230},
                "size":{
                  "width":660,
                  "height":210}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/test1/regen/u6.png"}},
{
          "id":"9e0da5e0b05d492bad90f0ea05d2c959",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":250},
            "size":{
              "width":440,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"427d17f448004b0e8bf0c2a8b596be20",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":29},
                "size":{
                  "width":147,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8851eff22390475e967246ed0267c6c5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":29},
                    "size":{
                      "width":147,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/test1/regen/u15.png"}},
{
              "id":"9a7e1b3a50584933aa99189363720cd8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":59},
                "size":{
                  "width":147,
                  "height":32}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3170618910da49d6b497487e242dcc35",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":59},
                    "size":{
                      "width":147,
                      "height":32}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/test1/regen/u21.png"}},
{
              "id":"3441d233baf74b7a9c73db4eea134cc8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":147,
                  "y":29},
                "size":{
                  "width":147,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bf189ee8ad0c47ce8e5c3711799f0b48",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":147,
                      "y":29},
                    "size":{
                      "width":147,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/test1/regen/u15.png"}},
{
              "id":"85fdb5deece148859d6957ff78a89a7c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":147,
                  "y":59},
                "size":{
                  "width":147,
                  "height":32}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ec8296e2c3864825bfc1f07ce6156c12",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":147,
                      "y":59},
                    "size":{
                      "width":147,
                      "height":32}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/test1/regen/u21.png"}},
{
              "id":"de2f9fabd1d34c63bd918f3cc899e14a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":29},
                "size":{
                  "width":146,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ec3bac3df86f4045a9ac806fc40dc443",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":29},
                    "size":{
                      "width":146,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/test1/regen/u19.png"}},
{
              "id":"3ab182212a85409182778cf628a2b70b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":59},
                "size":{
                  "width":146,
                  "height":32}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1efd7c78751d47b8a57774b2fab5e7cb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":59},
                    "size":{
                      "width":146,
                      "height":32}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/test1/regen/u25.png"}},
{
              "id":"6cb3bfef5b474aa6bc05cb533bebd86c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":91},
                "size":{
                  "width":147,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9a05727a31d54e489deb47e3a9fe6652",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":91},
                    "size":{
                      "width":147,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/test1/regen/u27.png"}},
{
              "id":"1e599c2ae642402b869efb6109da78a8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":147,
                  "y":91},
                "size":{
                  "width":147,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"77c5766d172d4fdd9aed6861e8ef7b62",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":147,
                      "y":91},
                    "size":{
                      "width":147,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/test1/regen/u27.png"}},
{
              "id":"c43aa0a4cd6e4590a4ab38c1ef026b29",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":91},
                "size":{
                  "width":146,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e3a058aa0232462ca673992f03a3f530",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":91},
                    "size":{
                      "width":146,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/test1/regen/u31.png"}},
{
              "id":"ea4ad8d9945347ab92df7ff6e854fd2d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":147,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"80f5ff51dcac4854a30a4817d0bc62e4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":147,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/test1/regen/u9.png"}},
{
              "id":"a1a0b767f4284e878bb1c4cdc744945f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":147,
                  "y":0},
                "size":{
                  "width":147,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2778d1bea3b645af90eff69b6b1a15c8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":147,
                      "y":0},
                    "size":{
                      "width":147,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/test1/regen/u9.png"}},
{
              "id":"666be6ab3cdd46df8529faf72881ab75",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":0},
                "size":{
                  "width":146,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"21b0975247b745fbb1c3605891cda915",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":0},
                    "size":{
                      "width":146,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/test1/regen/u13.png"}}]},
{
          "id":"d3936bad03734ab5a66262765eaed03c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":207,
              "y":250},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3e3e3eebc4a42bab73539d081e6d66a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":207,
                  "y":250},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"995c4257f59b496fa069ba51439e9e62",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":207,
              "y":390},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a68a9c25a634433a33167ffe1a11eec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":207,
                  "y":390},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe08a96089be43fdb8ef4fb1bf6e8b19",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":388},
            "size":{
              "width":190,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"011ccacf8b554fe1a7fa3897b7917dc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":388},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/test1/regen/u37.png"}},
{
          "id":"5bf02aaf46724905b81d4d84874bb91c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":770,
              "y":475},
            "size":{
              "width":70,
              "height":35}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 菜单页面",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"6648aff7a59d481dbc9458951285f44f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":388},
            "size":{
              "width":74,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 评定成绩",
                      "target":{
                        "targetType":"page",
                        "url":"评定成绩.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "1dc34aff5816461b9ceb772e26d65b6f":{
      "scriptId":"u0"},
    "ab4e1b57bba44f8e9cebe163d0e659e9":{
      "scriptId":"u1"},
    "8faebd7904bb4d4bbe805c82315d165d":{
      "scriptId":"u2"},
    "b8935c56731b4613a1e27d0a235985a8":{
      "scriptId":"u3"},
    "d4af4b335c7e446c883b7571790ae4e9":{
      "scriptId":"u4"},
    "d4f5878d42c94763ace901a6cafbcc8f":{
      "scriptId":"u5"},
    "8c4a263022bf46e8b256ae0db0697a74":{
      "scriptId":"u6"},
    "829c577e306c4b61be3a07c6960adeca":{
      "scriptId":"u7"},
    "9e0da5e0b05d492bad90f0ea05d2c959":{
      "scriptId":"u8"},
    "ea4ad8d9945347ab92df7ff6e854fd2d":{
      "scriptId":"u9"},
    "80f5ff51dcac4854a30a4817d0bc62e4":{
      "scriptId":"u10"},
    "a1a0b767f4284e878bb1c4cdc744945f":{
      "scriptId":"u11"},
    "2778d1bea3b645af90eff69b6b1a15c8":{
      "scriptId":"u12"},
    "666be6ab3cdd46df8529faf72881ab75":{
      "scriptId":"u13"},
    "21b0975247b745fbb1c3605891cda915":{
      "scriptId":"u14"},
    "427d17f448004b0e8bf0c2a8b596be20":{
      "scriptId":"u15"},
    "8851eff22390475e967246ed0267c6c5":{
      "scriptId":"u16"},
    "3441d233baf74b7a9c73db4eea134cc8":{
      "scriptId":"u17"},
    "bf189ee8ad0c47ce8e5c3711799f0b48":{
      "scriptId":"u18"},
    "de2f9fabd1d34c63bd918f3cc899e14a":{
      "scriptId":"u19"},
    "ec3bac3df86f4045a9ac806fc40dc443":{
      "scriptId":"u20"},
    "9a7e1b3a50584933aa99189363720cd8":{
      "scriptId":"u21"},
    "3170618910da49d6b497487e242dcc35":{
      "scriptId":"u22"},
    "85fdb5deece148859d6957ff78a89a7c":{
      "scriptId":"u23"},
    "ec8296e2c3864825bfc1f07ce6156c12":{
      "scriptId":"u24"},
    "3ab182212a85409182778cf628a2b70b":{
      "scriptId":"u25"},
    "1efd7c78751d47b8a57774b2fab5e7cb":{
      "scriptId":"u26"},
    "6cb3bfef5b474aa6bc05cb533bebd86c":{
      "scriptId":"u27"},
    "9a05727a31d54e489deb47e3a9fe6652":{
      "scriptId":"u28"},
    "1e599c2ae642402b869efb6109da78a8":{
      "scriptId":"u29"},
    "77c5766d172d4fdd9aed6861e8ef7b62":{
      "scriptId":"u30"},
    "c43aa0a4cd6e4590a4ab38c1ef026b29":{
      "scriptId":"u31"},
    "e3a058aa0232462ca673992f03a3f530":{
      "scriptId":"u32"},
    "d3936bad03734ab5a66262765eaed03c":{
      "scriptId":"u33"},
    "c3e3e3eebc4a42bab73539d081e6d66a":{
      "scriptId":"u34"},
    "995c4257f59b496fa069ba51439e9e62":{
      "scriptId":"u35"},
    "1a68a9c25a634433a33167ffe1a11eec":{
      "scriptId":"u36"},
    "fe08a96089be43fdb8ef4fb1bf6e8b19":{
      "scriptId":"u37"},
    "011ccacf8b554fe1a7fa3897b7917dc9":{
      "scriptId":"u38"},
    "5bf02aaf46724905b81d4d84874bb91c":{
      "scriptId":"u39"},
    "6648aff7a59d481dbc9458951285f44f":{
      "scriptId":"u40"}}});