$axure.loadCurrentPage({
  "url":"学生选课.html",
  "generationDate":new Date(1528106904139.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"294cd10959174f3baabec734804a01eb",
    "type":"Axure:Page",
    "name":"学生选课",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9f357e6a919e456ca00dceab86c547ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":343.5,
              "y":122},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fba10a9f3214a968c5e6cefaefc6809",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":343.5,
                  "y":122},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"527078546de149088f99971601ed0c42",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":75,
              "y":140},
            "size":{
              "width":145,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8eadb44a27334f80bc1826d0f1baf2dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":75,
                  "y":140},
                "size":{
                  "width":145,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生选课/regen/u2.png"}},
{
          "id":"7923a4d5de194c0c9ebb9634fec60e0d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":174},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSelectionChange":{
              "description":"OnSelectionChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课程列表2",
                      "target":{
                        "targetType":"page",
                        "url":"课程列表2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}}},
{
          "id":"b4577f68bb5841afacf99bc8cb9f1c00",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":75,
              "y":174},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5aba5083f6be4c7db146670df1f84612",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":75,
                  "y":174},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0459ce56571744dbad4bca4dc32f52e8",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":525,
              "y":174},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"d18d8af4871647f4a23a6c2e8952f8d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":475,
              "y":174},
            "size":{
              "width":49,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a127658374f4e9fba26a77a62d44acf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":475,
                  "y":174},
                "size":{
                  "width":49,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4a132d26495410ba183b80a4e800743",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":250},
            "size":{
              "width":647,
              "height":701}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"755217ab990a4066bf1baedf4bd9cc46",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5f413533390b4b3980d37a3f7ff4dccb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生选课/regen/u11.png"}},
{
              "id":"9feca69057f14989ae149e792ae538cd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":113,
                  "height":163}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"665146073dfd40f6a11270c90e737e19",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":113,
                      "height":163}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生选课/regen/u21.png"}},
{
              "id":"bb3d3e1758194c0390b33a69a172749a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":193},
                "size":{
                  "width":113,
                  "height":154}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6c082c9bd7ac4def91888eb74f63935c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":193},
                    "size":{
                      "width":113,
                      "height":154}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生选课/regen/u31.png"}},
{
              "id":"98210610775a41fcb6400253049b1b6f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":0},
                "size":{
                  "width":146,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5386b73b1649419ea4cef90ae63c628a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":0},
                    "size":{
                      "width":146,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生选课/regen/u13.png"}},
{
              "id":"cb20cdc2f2274f9aaaf77f1615f14746",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":30},
                "size":{
                  "width":146,
                  "height":163}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a658f670861949fc8a1212ea77653be4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":30},
                    "size":{
                      "width":146,
                      "height":163}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生选课/regen/u23.png"}},
{
              "id":"2ca2434ddd1d4facbb82de23f3437278",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":193},
                "size":{
                  "width":146,
                  "height":154}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a33873bde43e4c7ea6050705d0618079",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":193},
                    "size":{
                      "width":146,
                      "height":154}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生选课/regen/u33.png"}},
{
              "id":"421ec2904dd34c7392eac199dd7f7076",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":259,
                  "y":0},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2bb9876eee3d44d3bcc6c1394f3dfc51",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":259,
                      "y":0},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生选课/regen/u15.png"}},
{
              "id":"d31bc839475742d3b558e69180ab80bc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":259,
                  "y":30},
                "size":{
                  "width":120,
                  "height":163}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9073112763e1424f90042a503364d855",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":259,
                      "y":30},
                    "size":{
                      "width":120,
                      "height":163}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生选课/regen/u25.png"}},
{
              "id":"a3148814524649dc8fb74245f11240c3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":259,
                  "y":193},
                "size":{
                  "width":120,
                  "height":154}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"38545c5496c2405ca1a3646d3d3bdc32",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":259,
                      "y":193},
                    "size":{
                      "width":120,
                      "height":154}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生选课/regen/u35.png"}},
{
              "id":"9f10549985b54a25a92fb074ec4428f6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":508,
                  "y":0},
                "size":{
                  "width":139,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"352460077ae9465ba6e2dda8761205d1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":508,
                      "y":0},
                    "size":{
                      "width":139,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生选课/regen/u19.png"}},
{
              "id":"ffe2ec9da5704c609e25b1da0ee82fd6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":508,
                  "y":30},
                "size":{
                  "width":139,
                  "height":163}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d6ecc528b98548e3a120b6f2f74c9178",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":508,
                      "y":30},
                    "size":{
                      "width":139,
                      "height":163}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生选课/regen/u29.png"}},
{
              "id":"7a9666b9609b4948b9c30cfe1d188460",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":508,
                  "y":193},
                "size":{
                  "width":139,
                  "height":154}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1b16c9471b0748988b3edf0b5cdecbf3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":508,
                      "y":193},
                    "size":{
                      "width":139,
                      "height":154}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生选课/regen/u39.png"}},
{
              "id":"5cc8368b10dc49fdb79d0b234b82c90f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":347},
                "size":{
                  "width":113,
                  "height":174}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"526ed24ce0d24e55892d36227c0c39b9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":347},
                    "size":{
                      "width":113,
                      "height":174}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生选课/regen/u41.png"}},
{
              "id":"a2d685c1832c47c39f3813d2cfed2c89",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":347},
                "size":{
                  "width":146,
                  "height":174}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d267b4887a7b4221ba92352192baaf67",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":347},
                    "size":{
                      "width":146,
                      "height":174}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生选课/regen/u43.png"}},
{
              "id":"0bb63d1a8c784a7799edace3207a0223",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":259,
                  "y":347},
                "size":{
                  "width":120,
                  "height":174}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"37eecd7a35a143778b25da7b5bf8c8e8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":259,
                      "y":347},
                    "size":{
                      "width":120,
                      "height":174}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生选课/regen/u45.png"}},
{
              "id":"1d5c0a9a3b6542b893a14ab149c78a4a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":508,
                  "y":347},
                "size":{
                  "width":139,
                  "height":174}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8a58a635b18642b089d5805e9c15a202",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":508,
                      "y":347},
                    "size":{
                      "width":139,
                      "height":174}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生选课/regen/u49.png"}},
{
              "id":"3b5b910244f54e368820be24835420c5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":521},
                "size":{
                  "width":113,
                  "height":180}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c29c2cfffa7d457087954b2354316acf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":521},
                    "size":{
                      "width":113,
                      "height":180}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生选课/regen/u51.png"}},
{
              "id":"da9fa015dcf840ee9ddad13ed7125f92",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":521},
                "size":{
                  "width":146,
                  "height":180}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"70e5edd35b804836847275243d21312d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":521},
                    "size":{
                      "width":146,
                      "height":180}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生选课/regen/u53.png"}},
{
              "id":"383cad3623574442b82ece10dbebb183",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":259,
                  "y":521},
                "size":{
                  "width":120,
                  "height":180}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4f10b6ba1f674533b4e617f42be2f1c8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":259,
                      "y":521},
                    "size":{
                      "width":120,
                      "height":180}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生选课/regen/u55.png"}},
{
              "id":"695179d7248443e882eb0dcb1040b0d5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":508,
                  "y":521},
                "size":{
                  "width":139,
                  "height":180}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b7ec887ee9824390b2e3ba91d09ee2d8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":508,
                      "y":521},
                    "size":{
                      "width":139,
                      "height":180}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生选课/regen/u59.png"}},
{
              "id":"408399236f2545a8a83a3b068af3be2c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":379,
                  "y":0},
                "size":{
                  "width":129,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"57f0f47d20464b91a465c0496fd95206",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":379,
                      "y":0},
                    "size":{
                      "width":129,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生选课/regen/u17.png"}},
{
              "id":"1522734017a44d3b97996ca6025ad7e9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":379,
                  "y":30},
                "size":{
                  "width":129,
                  "height":163}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"080bbc73206c43a68746f8375cc9fa22",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":379,
                      "y":30},
                    "size":{
                      "width":129,
                      "height":163}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生选课/regen/u27.png"}},
{
              "id":"9a721f88a0aa4f47aaa852002a0be4e7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":379,
                  "y":193},
                "size":{
                  "width":129,
                  "height":154}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"21615fe55ebc49fcb0ee2d987f7d907e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":379,
                      "y":193},
                    "size":{
                      "width":129,
                      "height":154}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生选课/regen/u37.png"}},
{
              "id":"72e3605101774e3eaf91be996ddf4793",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":379,
                  "y":347},
                "size":{
                  "width":129,
                  "height":174}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cf341a6efbc14ed3b75527c4e6f599b9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":379,
                      "y":347},
                    "size":{
                      "width":129,
                      "height":174}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生选课/regen/u47.png"}},
{
              "id":"881b75f761f949288600efa9d3f83024",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":379,
                  "y":521},
                "size":{
                  "width":129,
                  "height":180}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b19e4e8a01a545ae88aeb19f6219e5e9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":379,
                      "y":521},
                    "size":{
                      "width":129,
                      "height":180}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/学生选课/regen/u57.png"}}]},
{
          "id":"931ac3d69b1841abaf010fe479d997cf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":596,
              "y":320},
            "size":{
              "width":114,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39598af2f43d478691ee61585643b3c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":596,
                  "y":320},
                "size":{
                  "width":114,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生选课/regen/u61.png"}},
{
          "id":"0114c2e1bf2c4b77ad9263b7e1f355b1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":472},
            "size":{
              "width":110,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c5951d0a43d4ae08e51be575f524a64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":472},
                "size":{
                  "width":110,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生选课/regen/u63.png"}},
{
          "id":"6d285a8b34834792aab13c882d7c4b8a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":620},
            "size":{
              "width":120,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cef5d8cd0494f15b2b2fe51608e12e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":620},
                "size":{
                  "width":120,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生选课/regen/u65.png"}},
{
          "id":"dc1e9ef465dc49d5b7f3ccbfadfa1db5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":605,
              "y":800},
            "size":{
              "width":96,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21f26f7bfe1947dbab76f9a562782d79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":605,
                  "y":800},
                "size":{
                  "width":96,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生选课/regen/u67.png"}},
{
          "id":"8239571af3344fc3bf2e18bd141b8d95",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":216,
              "y":1011},
            "size":{
              "width":70,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 重新加载",
                      "target":{
                        "targetType":"reloadPage",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"9e5348d0ab264ef5ad6aa2d001805e52",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":476,
              "y":1011},
            "size":{
              "width":70,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 菜单页面",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"80aa7248997a41b8976d2571c72f8b35",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":75,
              "y":10},
            "size":{
              "width":650,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b834ade10c954c32a8499b64ca0373f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":75,
                  "y":10},
                "size":{
                  "width":650,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生选课/regen/u71.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "9f357e6a919e456ca00dceab86c547ea":{
      "scriptId":"u0"},
    "0fba10a9f3214a968c5e6cefaefc6809":{
      "scriptId":"u1"},
    "527078546de149088f99971601ed0c42":{
      "scriptId":"u2"},
    "8eadb44a27334f80bc1826d0f1baf2dd":{
      "scriptId":"u3"},
    "7923a4d5de194c0c9ebb9634fec60e0d":{
      "scriptId":"u4"},
    "b4577f68bb5841afacf99bc8cb9f1c00":{
      "scriptId":"u5"},
    "5aba5083f6be4c7db146670df1f84612":{
      "scriptId":"u6"},
    "0459ce56571744dbad4bca4dc32f52e8":{
      "scriptId":"u7"},
    "d18d8af4871647f4a23a6c2e8952f8d0":{
      "scriptId":"u8"},
    "7a127658374f4e9fba26a77a62d44acf":{
      "scriptId":"u9"},
    "a4a132d26495410ba183b80a4e800743":{
      "scriptId":"u10"},
    "755217ab990a4066bf1baedf4bd9cc46":{
      "scriptId":"u11"},
    "5f413533390b4b3980d37a3f7ff4dccb":{
      "scriptId":"u12"},
    "98210610775a41fcb6400253049b1b6f":{
      "scriptId":"u13"},
    "5386b73b1649419ea4cef90ae63c628a":{
      "scriptId":"u14"},
    "421ec2904dd34c7392eac199dd7f7076":{
      "scriptId":"u15"},
    "2bb9876eee3d44d3bcc6c1394f3dfc51":{
      "scriptId":"u16"},
    "408399236f2545a8a83a3b068af3be2c":{
      "scriptId":"u17"},
    "57f0f47d20464b91a465c0496fd95206":{
      "scriptId":"u18"},
    "9f10549985b54a25a92fb074ec4428f6":{
      "scriptId":"u19"},
    "352460077ae9465ba6e2dda8761205d1":{
      "scriptId":"u20"},
    "9feca69057f14989ae149e792ae538cd":{
      "scriptId":"u21"},
    "665146073dfd40f6a11270c90e737e19":{
      "scriptId":"u22"},
    "cb20cdc2f2274f9aaaf77f1615f14746":{
      "scriptId":"u23"},
    "a658f670861949fc8a1212ea77653be4":{
      "scriptId":"u24"},
    "d31bc839475742d3b558e69180ab80bc":{
      "scriptId":"u25"},
    "9073112763e1424f90042a503364d855":{
      "scriptId":"u26"},
    "1522734017a44d3b97996ca6025ad7e9":{
      "scriptId":"u27"},
    "080bbc73206c43a68746f8375cc9fa22":{
      "scriptId":"u28"},
    "ffe2ec9da5704c609e25b1da0ee82fd6":{
      "scriptId":"u29"},
    "d6ecc528b98548e3a120b6f2f74c9178":{
      "scriptId":"u30"},
    "bb3d3e1758194c0390b33a69a172749a":{
      "scriptId":"u31"},
    "6c082c9bd7ac4def91888eb74f63935c":{
      "scriptId":"u32"},
    "2ca2434ddd1d4facbb82de23f3437278":{
      "scriptId":"u33"},
    "a33873bde43e4c7ea6050705d0618079":{
      "scriptId":"u34"},
    "a3148814524649dc8fb74245f11240c3":{
      "scriptId":"u35"},
    "38545c5496c2405ca1a3646d3d3bdc32":{
      "scriptId":"u36"},
    "9a721f88a0aa4f47aaa852002a0be4e7":{
      "scriptId":"u37"},
    "21615fe55ebc49fcb0ee2d987f7d907e":{
      "scriptId":"u38"},
    "7a9666b9609b4948b9c30cfe1d188460":{
      "scriptId":"u39"},
    "1b16c9471b0748988b3edf0b5cdecbf3":{
      "scriptId":"u40"},
    "5cc8368b10dc49fdb79d0b234b82c90f":{
      "scriptId":"u41"},
    "526ed24ce0d24e55892d36227c0c39b9":{
      "scriptId":"u42"},
    "a2d685c1832c47c39f3813d2cfed2c89":{
      "scriptId":"u43"},
    "d267b4887a7b4221ba92352192baaf67":{
      "scriptId":"u44"},
    "0bb63d1a8c784a7799edace3207a0223":{
      "scriptId":"u45"},
    "37eecd7a35a143778b25da7b5bf8c8e8":{
      "scriptId":"u46"},
    "72e3605101774e3eaf91be996ddf4793":{
      "scriptId":"u47"},
    "cf341a6efbc14ed3b75527c4e6f599b9":{
      "scriptId":"u48"},
    "1d5c0a9a3b6542b893a14ab149c78a4a":{
      "scriptId":"u49"},
    "8a58a635b18642b089d5805e9c15a202":{
      "scriptId":"u50"},
    "3b5b910244f54e368820be24835420c5":{
      "scriptId":"u51"},
    "c29c2cfffa7d457087954b2354316acf":{
      "scriptId":"u52"},
    "da9fa015dcf840ee9ddad13ed7125f92":{
      "scriptId":"u53"},
    "70e5edd35b804836847275243d21312d":{
      "scriptId":"u54"},
    "383cad3623574442b82ece10dbebb183":{
      "scriptId":"u55"},
    "4f10b6ba1f674533b4e617f42be2f1c8":{
      "scriptId":"u56"},
    "881b75f761f949288600efa9d3f83024":{
      "scriptId":"u57"},
    "b19e4e8a01a545ae88aeb19f6219e5e9":{
      "scriptId":"u58"},
    "695179d7248443e882eb0dcb1040b0d5":{
      "scriptId":"u59"},
    "b7ec887ee9824390b2e3ba91d09ee2d8":{
      "scriptId":"u60"},
    "931ac3d69b1841abaf010fe479d997cf":{
      "scriptId":"u61"},
    "39598af2f43d478691ee61585643b3c3":{
      "scriptId":"u62"},
    "0114c2e1bf2c4b77ad9263b7e1f355b1":{
      "scriptId":"u63"},
    "8c5951d0a43d4ae08e51be575f524a64":{
      "scriptId":"u64"},
    "6d285a8b34834792aab13c882d7c4b8a":{
      "scriptId":"u65"},
    "9cef5d8cd0494f15b2b2fe51608e12e5":{
      "scriptId":"u66"},
    "dc1e9ef465dc49d5b7f3ccbfadfa1db5":{
      "scriptId":"u67"},
    "21f26f7bfe1947dbab76f9a562782d79":{
      "scriptId":"u68"},
    "8239571af3344fc3bf2e18bd141b8d95":{
      "scriptId":"u69"},
    "9e5348d0ab264ef5ad6aa2d001805e52":{
      "scriptId":"u70"},
    "80aa7248997a41b8976d2571c72f8b35":{
      "scriptId":"u71"},
    "b834ade10c954c32a8499b64ca0373f8":{
      "scriptId":"u72"}}});