$axure.loadCurrentPage({
  "url":"选学期.html",
  "generationDate":new Date(1528106910086.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"530b2e2f9faf48c3bf2a5a69f26df5ed",
    "type":"Axure:Page",
    "name":"选学期",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3a12e6c478894ad4a66e699254ac65d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":342,
              "y":122},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"029a21f8c5744dfba0f7af204a14b257",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":342,
                  "y":122},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13fc4680a5e1492488b40ca04cabdcfa",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":66,
              "y":136},
            "size":{
              "width":145,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef41bf7b534a46908932cdf38e839538",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":66,
                  "y":136},
                "size":{
                  "width":145,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选学期/regen/u2.png"}},
{
          "id":"3c1f8c7c9d4a447e8b6824361fad4283",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":172.5},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSelectionChange":{
              "description":"OnSelectionChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课程列表2",
                      "target":{
                        "targetType":"page",
                        "url":"课程列表2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}}},
{
          "id":"e60e73471f52479a89aff44f74ac4c6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":66,
              "y":172},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f761762e9e3140c593f8eb2b41620c34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":66,
                  "y":172},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e69652ed2bc24744a6c19c56d207943e",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":516,
              "y":174},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"fc97376060cb4d67ba0b91b87e63ee62",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":467,
              "y":174},
            "size":{
              "width":49,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f6f657b49624ef5b3263fd23482d21e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":467,
                  "y":174},
                "size":{
                  "width":49,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7674128f46443f5bcea529549314045",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":260},
            "size":{
              "width":650,
              "height":690}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e7c00d054f84c4d86985bf0a5b593bb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3cd415b6f1a34df3af66b40fea0555e4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选学期/regen/u11.png"}},
{
              "id":"a243fb00ec1d4d40b90d078e1a19f122",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":113,
                  "height":163}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"56fb07744ea641ab9f6918612c8c0ab3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":113,
                      "height":163}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选学期/regen/u21.png"}},
{
              "id":"e02d945bcd2440df92ae439bf1ecee51",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":193},
                "size":{
                  "width":113,
                  "height":154}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"52c6fcf9d9d4444e8f3fdc979bddd365",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":193},
                    "size":{
                      "width":113,
                      "height":154}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选学期/regen/u31.png"}},
{
              "id":"3c255ab3ca8e4513a1bbc9f68b60cfc4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":0},
                "size":{
                  "width":147,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6c057fde8d2e4aed987fba92da9affbb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":0},
                    "size":{
                      "width":147,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选学期/regen/u13.png"}},
{
              "id":"6eae36a158214104bbd777340c41d864",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":30},
                "size":{
                  "width":147,
                  "height":163}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"34f2a6fc550f47e4bfe72eb816cab9e3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":30},
                    "size":{
                      "width":147,
                      "height":163}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选学期/regen/u23.png"}},
{
              "id":"eb2cb949a3bd4947bd26f101c014c522",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":193},
                "size":{
                  "width":147,
                  "height":154}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"aab93fd40ced4e84987a16908272fc94",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":193},
                    "size":{
                      "width":147,
                      "height":154}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选学期/regen/u33.png"}},
{
              "id":"c41bed5f0855433cb7c243b774682624",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":260,
                  "y":0},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6f46a0a99f994d829aafb0ac190b7bea",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":260,
                      "y":0},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选学期/regen/u15.png"}},
{
              "id":"7d31ba04e21747079ab2681273fc1822",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":260,
                  "y":30},
                "size":{
                  "width":120,
                  "height":163}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a1c6c760f80d4c8d9a7eafc91cb8f3e7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":260,
                      "y":30},
                    "size":{
                      "width":120,
                      "height":163}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选学期/regen/u25.png"}},
{
              "id":"fe6c0ecbac0d419396bc40f459378cd9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":260,
                  "y":193},
                "size":{
                  "width":120,
                  "height":154}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cd7aec5432e5471690a9865cdebe8f60",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":260,
                      "y":193},
                    "size":{
                      "width":120,
                      "height":154}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选学期/regen/u35.png"}},
{
              "id":"1a8832ebc2834575abf0afff9821cc23",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":510,
                  "y":0},
                "size":{
                  "width":140,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dffc27707cdf4c879bf8ae8fcbb6600b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":510,
                      "y":0},
                    "size":{
                      "width":140,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选学期/regen/u19.png"}},
{
              "id":"635af8c3fdc540a4bea52b8109d3896d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":510,
                  "y":30},
                "size":{
                  "width":140,
                  "height":163}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2f320960aab64de58ff12b38252a303a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":510,
                      "y":30},
                    "size":{
                      "width":140,
                      "height":163}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选学期/regen/u29.png"}},
{
              "id":"ec7b07b9fce14b428646df92a34954f0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":510,
                  "y":193},
                "size":{
                  "width":140,
                  "height":154}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b06c84556de54fbca7327081841afacc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":510,
                      "y":193},
                    "size":{
                      "width":140,
                      "height":154}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选学期/regen/u39.png"}},
{
              "id":"52651afae6104856a2b90876bdc759d0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":347},
                "size":{
                  "width":113,
                  "height":174}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a4dc95c5218a490eac14e1a67b30d008",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":347},
                    "size":{
                      "width":113,
                      "height":174}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选学期/regen/u41.png"}},
{
              "id":"d136cc02234843718b494355d7d52173",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":347},
                "size":{
                  "width":147,
                  "height":174}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3ec3040846704d2daa581d5dd531591e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":347},
                    "size":{
                      "width":147,
                      "height":174}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选学期/regen/u43.png"}},
{
              "id":"bce9616725c049cb8dcde3eb81b563d0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":260,
                  "y":347},
                "size":{
                  "width":120,
                  "height":174}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0a0d3fd6d1e34b7b8ba14ee6b6f9e6a1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":260,
                      "y":347},
                    "size":{
                      "width":120,
                      "height":174}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选学期/regen/u45.png"}},
{
              "id":"7420a64619764d019ac3df71a1d3a4a3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":510,
                  "y":347},
                "size":{
                  "width":140,
                  "height":174}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"14beb5c7c3af49a18a063e34a8e72f4f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":510,
                      "y":347},
                    "size":{
                      "width":140,
                      "height":174}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选学期/regen/u49.png"}},
{
              "id":"65c2cceacf8f48c49d1c3f237fc0dd61",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":521},
                "size":{
                  "width":113,
                  "height":169}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"339c9024f5d549daa368706ded17e804",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":521},
                    "size":{
                      "width":113,
                      "height":169}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选学期/regen/u51.png"}},
{
              "id":"59781aaf99764086897a497917152389",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":521},
                "size":{
                  "width":147,
                  "height":169}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d8e944ee5e944863ad1f70ced0f6f6e0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":521},
                    "size":{
                      "width":147,
                      "height":169}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选学期/regen/u53.png"}},
{
              "id":"76bde1fcb71942ccbd5f172cf6da6c95",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":260,
                  "y":521},
                "size":{
                  "width":120,
                  "height":169}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b595e0593f3a4ac4b933cc8c0bebba9c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":260,
                      "y":521},
                    "size":{
                      "width":120,
                      "height":169}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选学期/regen/u55.png"}},
{
              "id":"423b9fc2b1934d2892523fdf6059094e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":510,
                  "y":521},
                "size":{
                  "width":140,
                  "height":169}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b81a5320bca84166aea53d6648f0423e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":510,
                      "y":521},
                    "size":{
                      "width":140,
                      "height":169}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选学期/regen/u59.png"}},
{
              "id":"52850643a8b34d2ba482c3b59b3e57d0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":380,
                  "y":0},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"207343bce0d343b2a87734aaa2601433",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":380,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选学期/regen/u17.png"}},
{
              "id":"ed8f97e4201e487caacd65bfd97e60e5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":380,
                  "y":30},
                "size":{
                  "width":130,
                  "height":163}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"204d66cc379746f49ce73df1c845e06d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":380,
                      "y":30},
                    "size":{
                      "width":130,
                      "height":163}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选学期/regen/u27.png"}},
{
              "id":"f0d4b32f4a064371b29d3f3926121440",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":380,
                  "y":193},
                "size":{
                  "width":130,
                  "height":154}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"23ae1a6c8a71403784f08c3b3c002dc9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":380,
                      "y":193},
                    "size":{
                      "width":130,
                      "height":154}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选学期/regen/u37.png"}},
{
              "id":"919f2b0e7a1a4cb0b004b897168b7f32",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":380,
                  "y":347},
                "size":{
                  "width":130,
                  "height":174}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bf0a488a0eb24fcf9c15f06e041ce13a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":380,
                      "y":347},
                    "size":{
                      "width":130,
                      "height":174}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选学期/regen/u47.png"}},
{
              "id":"07e5f4bf060d49998c4288334811197b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":380,
                  "y":521},
                "size":{
                  "width":130,
                  "height":169}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3b8f8c1ec6224a82893225a5af0528a6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":380,
                      "y":521},
                    "size":{
                      "width":130,
                      "height":169}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选学期/regen/u57.png"}}]},
{
          "id":"6c69e692c0654fc0ad04be55e7b641fa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":589,
              "y":321},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b26c22e389bc4f96991007f08197862b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":589,
                  "y":321},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选学期/regen/u61.png"}},
{
          "id":"474c3b3632df4a0784032a5a4709f1ae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":473},
            "size":{
              "width":106,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acf945511e464f8a9d79faf2a9987cba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":473},
                "size":{
                  "width":106,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选学期/regen/u63.png"}},
{
          "id":"44339e2d7b4549e68195a9ae76a13810",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":591,
              "y":621},
            "size":{
              "width":115,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e768eaaf99ca45628c906bc533ab36d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":591,
                  "y":621},
                "size":{
                  "width":115,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选学期/regen/u65.png"}},
{
          "id":"7e751e27b694476b92a030896cdd03ac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":598,
              "y":810},
            "size":{
              "width":92,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08423e5e4f67472c97994c1ec7402a0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":598,
                  "y":810},
                "size":{
                  "width":92,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选学期/regen/u67.png"}},
{
          "id":"c117d8c962ac497cb2e35c0f51f4fe34",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":649,
              "y":1040},
            "size":{
              "width":67,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 菜单页面",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"9e697e8f4de546f499f982aeee63e48a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":65.5,
              "y":10},
            "size":{
              "width":650,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70ea8c0e1d374a86b02326f42f9e64de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":65.5,
                  "y":10},
                "size":{
                  "width":650,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选学期/regen/u70.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "3a12e6c478894ad4a66e699254ac65d0":{
      "scriptId":"u0"},
    "029a21f8c5744dfba0f7af204a14b257":{
      "scriptId":"u1"},
    "13fc4680a5e1492488b40ca04cabdcfa":{
      "scriptId":"u2"},
    "ef41bf7b534a46908932cdf38e839538":{
      "scriptId":"u3"},
    "3c1f8c7c9d4a447e8b6824361fad4283":{
      "scriptId":"u4"},
    "e60e73471f52479a89aff44f74ac4c6f":{
      "scriptId":"u5"},
    "f761762e9e3140c593f8eb2b41620c34":{
      "scriptId":"u6"},
    "e69652ed2bc24744a6c19c56d207943e":{
      "scriptId":"u7"},
    "fc97376060cb4d67ba0b91b87e63ee62":{
      "scriptId":"u8"},
    "0f6f657b49624ef5b3263fd23482d21e":{
      "scriptId":"u9"},
    "e7674128f46443f5bcea529549314045":{
      "scriptId":"u10"},
    "8e7c00d054f84c4d86985bf0a5b593bb":{
      "scriptId":"u11"},
    "3cd415b6f1a34df3af66b40fea0555e4":{
      "scriptId":"u12"},
    "3c255ab3ca8e4513a1bbc9f68b60cfc4":{
      "scriptId":"u13"},
    "6c057fde8d2e4aed987fba92da9affbb":{
      "scriptId":"u14"},
    "c41bed5f0855433cb7c243b774682624":{
      "scriptId":"u15"},
    "6f46a0a99f994d829aafb0ac190b7bea":{
      "scriptId":"u16"},
    "52850643a8b34d2ba482c3b59b3e57d0":{
      "scriptId":"u17"},
    "207343bce0d343b2a87734aaa2601433":{
      "scriptId":"u18"},
    "1a8832ebc2834575abf0afff9821cc23":{
      "scriptId":"u19"},
    "dffc27707cdf4c879bf8ae8fcbb6600b":{
      "scriptId":"u20"},
    "a243fb00ec1d4d40b90d078e1a19f122":{
      "scriptId":"u21"},
    "56fb07744ea641ab9f6918612c8c0ab3":{
      "scriptId":"u22"},
    "6eae36a158214104bbd777340c41d864":{
      "scriptId":"u23"},
    "34f2a6fc550f47e4bfe72eb816cab9e3":{
      "scriptId":"u24"},
    "7d31ba04e21747079ab2681273fc1822":{
      "scriptId":"u25"},
    "a1c6c760f80d4c8d9a7eafc91cb8f3e7":{
      "scriptId":"u26"},
    "ed8f97e4201e487caacd65bfd97e60e5":{
      "scriptId":"u27"},
    "204d66cc379746f49ce73df1c845e06d":{
      "scriptId":"u28"},
    "635af8c3fdc540a4bea52b8109d3896d":{
      "scriptId":"u29"},
    "2f320960aab64de58ff12b38252a303a":{
      "scriptId":"u30"},
    "e02d945bcd2440df92ae439bf1ecee51":{
      "scriptId":"u31"},
    "52c6fcf9d9d4444e8f3fdc979bddd365":{
      "scriptId":"u32"},
    "eb2cb949a3bd4947bd26f101c014c522":{
      "scriptId":"u33"},
    "aab93fd40ced4e84987a16908272fc94":{
      "scriptId":"u34"},
    "fe6c0ecbac0d419396bc40f459378cd9":{
      "scriptId":"u35"},
    "cd7aec5432e5471690a9865cdebe8f60":{
      "scriptId":"u36"},
    "f0d4b32f4a064371b29d3f3926121440":{
      "scriptId":"u37"},
    "23ae1a6c8a71403784f08c3b3c002dc9":{
      "scriptId":"u38"},
    "ec7b07b9fce14b428646df92a34954f0":{
      "scriptId":"u39"},
    "b06c84556de54fbca7327081841afacc":{
      "scriptId":"u40"},
    "52651afae6104856a2b90876bdc759d0":{
      "scriptId":"u41"},
    "a4dc95c5218a490eac14e1a67b30d008":{
      "scriptId":"u42"},
    "d136cc02234843718b494355d7d52173":{
      "scriptId":"u43"},
    "3ec3040846704d2daa581d5dd531591e":{
      "scriptId":"u44"},
    "bce9616725c049cb8dcde3eb81b563d0":{
      "scriptId":"u45"},
    "0a0d3fd6d1e34b7b8ba14ee6b6f9e6a1":{
      "scriptId":"u46"},
    "919f2b0e7a1a4cb0b004b897168b7f32":{
      "scriptId":"u47"},
    "bf0a488a0eb24fcf9c15f06e041ce13a":{
      "scriptId":"u48"},
    "7420a64619764d019ac3df71a1d3a4a3":{
      "scriptId":"u49"},
    "14beb5c7c3af49a18a063e34a8e72f4f":{
      "scriptId":"u50"},
    "65c2cceacf8f48c49d1c3f237fc0dd61":{
      "scriptId":"u51"},
    "339c9024f5d549daa368706ded17e804":{
      "scriptId":"u52"},
    "59781aaf99764086897a497917152389":{
      "scriptId":"u53"},
    "d8e944ee5e944863ad1f70ced0f6f6e0":{
      "scriptId":"u54"},
    "76bde1fcb71942ccbd5f172cf6da6c95":{
      "scriptId":"u55"},
    "b595e0593f3a4ac4b933cc8c0bebba9c":{
      "scriptId":"u56"},
    "07e5f4bf060d49998c4288334811197b":{
      "scriptId":"u57"},
    "3b8f8c1ec6224a82893225a5af0528a6":{
      "scriptId":"u58"},
    "423b9fc2b1934d2892523fdf6059094e":{
      "scriptId":"u59"},
    "b81a5320bca84166aea53d6648f0423e":{
      "scriptId":"u60"},
    "6c69e692c0654fc0ad04be55e7b641fa":{
      "scriptId":"u61"},
    "b26c22e389bc4f96991007f08197862b":{
      "scriptId":"u62"},
    "474c3b3632df4a0784032a5a4709f1ae":{
      "scriptId":"u63"},
    "acf945511e464f8a9d79faf2a9987cba":{
      "scriptId":"u64"},
    "44339e2d7b4549e68195a9ae76a13810":{
      "scriptId":"u65"},
    "e768eaaf99ca45628c906bc533ab36d6":{
      "scriptId":"u66"},
    "7e751e27b694476b92a030896cdd03ac":{
      "scriptId":"u67"},
    "08423e5e4f67472c97994c1ec7402a0f":{
      "scriptId":"u68"},
    "c117d8c962ac497cb2e35c0f51f4fe34":{
      "scriptId":"u69"},
    "9e697e8f4de546f499f982aeee63e48a":{
      "scriptId":"u70"},
    "70ea8c0e1d374a86b02326f42f9e64de":{
      "scriptId":"u71"}}});