$axure.loadCurrentPage({
  "url":"课程列表.html",
  "generationDate":new Date(1528106921741.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2f753dcbfefa48e4a15d26fd10914dda",
    "type":"Axure:Page",
    "name":"课程列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4c5b5eaf41704ddca6ba937e876a3fdf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":335,
              "y":126},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d05fa9d0561c4a4c980b1f92c9b5d5b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":335,
                  "y":126},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61f267adb1ad4007b46036697a9d61e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":60,
              "y":136},
            "size":{
              "width":145,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5795d5f5468d4c05871fe1f756b82bee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":60,
                  "y":136},
                "size":{
                  "width":145,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课程列表/regen/u2.png"}},
{
          "id":"b1d67df57891432fbc34aa98d5cbd426",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":109,
              "y":170},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSelectionChange":{
              "description":"OnSelectionChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课程列表1",
                      "target":{
                        "targetType":"page",
                        "url":"课程列表1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}}},
{
          "id":"86e16e18b64743afb42ba83cc1f9dca4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":60,
              "y":170},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dc8939a5c6a4225883d9f8eab3a2924",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":60,
                  "y":170},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85f58c1de9c94178ac05a406a1c844c5",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":250},
            "size":{
              "width":650,
              "height":681}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27d13096f5f04a509fdecd65b9e26105",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":139,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a926b0072cce461c8772e3920a2dd0cf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":139,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/regen/u8.png"}},
{
              "id":"403df68cf100469896aa92ec7006e812",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":139,
                  "height":153}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4ca7747593864230affefc2bd0399ac1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":139,
                      "height":153}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/regen/u16.png"}},
{
              "id":"e932c758bf5f4ee2b8ca6c8b4e7b2af3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":183},
                "size":{
                  "width":139,
                  "height":154}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2c91d95220414fbbacd93b84d8887697",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":183},
                    "size":{
                      "width":139,
                      "height":154}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/regen/u24.png"}},
{
              "id":"0583fa8eeb8d43028c597acd2e1ae0b1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":139,
                  "y":0},
                "size":{
                  "width":180,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"790e3ad163e84636884f496a4035b563",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":139,
                      "y":0},
                    "size":{
                      "width":180,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/regen/u10.png"}},
{
              "id":"9d2d674b04bf41a0a4fa1051ceebb975",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":139,
                  "y":30},
                "size":{
                  "width":180,
                  "height":153}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0972ec3f035b47edb378ce458e4a01e5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":139,
                      "y":30},
                    "size":{
                      "width":180,
                      "height":153}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/regen/u18.png"}},
{
              "id":"5fbe9bfed6ad4bdc81cbf8f28ca5879c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":139,
                  "y":183},
                "size":{
                  "width":180,
                  "height":154}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2c2622437569472c86cde425f5469ff2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":139,
                      "y":183},
                    "size":{
                      "width":180,
                      "height":154}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/regen/u26.png"}},
{
              "id":"8ea20c0407c648cfb83063c0f93c1a39",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":319,
                  "y":0},
                "size":{
                  "width":147,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1f3a42d1ce244665be6b34fe2c3d271b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":319,
                      "y":0},
                    "size":{
                      "width":147,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/regen/u12.png"}},
{
              "id":"eaa3f9d2cca5421aa865f193c8911f70",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":319,
                  "y":30},
                "size":{
                  "width":147,
                  "height":153}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"52f78e6b9a2d46d59e273e69a15898d0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":319,
                      "y":30},
                    "size":{
                      "width":147,
                      "height":153}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/regen/u20.png"}},
{
              "id":"9ce8f0dcf1e94678a335d80258d8de28",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":319,
                  "y":183},
                "size":{
                  "width":147,
                  "height":154}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4341297a00984eabae211ea0f4f44a62",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":319,
                      "y":183},
                    "size":{
                      "width":147,
                      "height":154}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/regen/u28.png"}},
{
              "id":"c04d5482b4944f3ebd0af0109c4a92bc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":466,
                  "y":0},
                "size":{
                  "width":184,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4930e60651de4644aeeae681666c62c3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":466,
                      "y":0},
                    "size":{
                      "width":184,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/regen/u14.png"}},
{
              "id":"0b0e42c804d642d29356fa937e51b899",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":466,
                  "y":30},
                "size":{
                  "width":184,
                  "height":153}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"53f6c12e4c4c4b8a870a9d7a50e7bc23",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":466,
                      "y":30},
                    "size":{
                      "width":184,
                      "height":153}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/regen/u22.png"}},
{
              "id":"932023efdb364bb588be4a785c8b8abc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":466,
                  "y":183},
                "size":{
                  "width":184,
                  "height":154}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2ce974e5ba5348bf9eaabdfd8f83f1fa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":466,
                      "y":183},
                    "size":{
                      "width":184,
                      "height":154}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/regen/u30.png"}},
{
              "id":"a947eb4b26754d6f97045a7ba9678671",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":337},
                "size":{
                  "width":139,
                  "height":174}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a733ed0de79a4ca18ad2538427fa65df",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":337},
                    "size":{
                      "width":139,
                      "height":174}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/regen/u32.png"}},
{
              "id":"dcb1dbd8bd0f415a90a61b7aff5bbdec",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":139,
                  "y":337},
                "size":{
                  "width":180,
                  "height":174}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"02ca2a9dc0e145158d393634a94ec887",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":139,
                      "y":337},
                    "size":{
                      "width":180,
                      "height":174}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/regen/u34.png"}},
{
              "id":"f91708ea1dbf418c808fe0e4ff408666",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":319,
                  "y":337},
                "size":{
                  "width":147,
                  "height":174}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0ad7226253a9466fae698e3bd91b5ccb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":319,
                      "y":337},
                    "size":{
                      "width":147,
                      "height":174}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/regen/u36.png"}},
{
              "id":"1f70d488935245d9b321c2c14355df77",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":466,
                  "y":337},
                "size":{
                  "width":184,
                  "height":174}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5f7c748c3a8e4b09bd05e5bca26a3b25",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":466,
                      "y":337},
                    "size":{
                      "width":184,
                      "height":174}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/regen/u38.png"}},
{
              "id":"741999195b4a4d2da5eceb9f2dfa5a99",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":511},
                "size":{
                  "width":139,
                  "height":170}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"52fc947b65664b56a576522d3e549cbc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":511},
                    "size":{
                      "width":139,
                      "height":170}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/regen/u40.png"}},
{
              "id":"598e55cc2f854b568c1041e382f6548d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":139,
                  "y":511},
                "size":{
                  "width":180,
                  "height":170}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e4dd3c8f7003420f959657a439f6fda8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":139,
                      "y":511},
                    "size":{
                      "width":180,
                      "height":170}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/regen/u42.png"}},
{
              "id":"9a587a4fa2664e6f8968012a8226f371",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":319,
                  "y":511},
                "size":{
                  "width":147,
                  "height":170}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"295b10b4b02c4cf6988bbf86de8cdc53",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":319,
                      "y":511},
                    "size":{
                      "width":147,
                      "height":170}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/regen/u44.png"}},
{
              "id":"bd436f9726324ae187888ef4959d7482",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":466,
                  "y":511},
                "size":{
                  "width":184,
                  "height":170}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0913dc1e9ff9405fbd839080075cde63",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":466,
                      "y":511},
                    "size":{
                      "width":184,
                      "height":170}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/课程列表/regen/u46.png"}}]},
{
          "id":"80261bd5299440f58c22ce3f6856e004",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":170},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"eb87f25265194476943871ec84cdeb9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":461,
              "y":173},
            "size":{
              "width":49,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b8a6cc16ea64d05a317189353f51296",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":461,
                  "y":173},
                "size":{
                  "width":49,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3f1161d9bbe841a5872a4bdac2b8c851",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":613,
              "y":985},
            "size":{
              "width":97,
              "height":35}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 菜单页面",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"f8f9d270587f4232bb44586b77762d0d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":542,
              "y":300},
            "size":{
              "width":134,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0962d79e6d244ac49a68e96733735795",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":542,
                  "y":300},
                "size":{
                  "width":134,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课程列表/regen/u52.png"}},
{
          "id":"6a0203a44b004dca828fe34eb9499589",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":547,
              "y":452},
            "size":{
              "width":130,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6737965b82f044a887a0685afa0eb77e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":547,
                  "y":452},
                "size":{
                  "width":130,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课程列表/regen/u54.png"}},
{
          "id":"f9cce98eb79d4535bae134fb9ee2fe44",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":553,
              "y":600},
            "size":{
              "width":142,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a36e9ad4dcbd439fabafefcb17441930",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":553,
                  "y":600},
                "size":{
                  "width":142,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课程列表/regen/u56.png"}},
{
          "id":"9f9b573fe3d54387a72dc3c5283d9a07",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":564,
              "y":780},
            "size":{
              "width":113,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a33bb3572aa42e6a15171972703d324",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":564,
                  "y":780},
                "size":{
                  "width":113,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课程列表/regen/u58.png"}},
{
          "id":"c68155f40dc548b0a1f16c0ea74e3fba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":60,
              "y":20},
            "size":{
              "width":650,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62b1811a2e934f158c349ee1095d1786",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":60,
                  "y":20},
                "size":{
                  "width":650,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课程列表/regen/u60.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4c5b5eaf41704ddca6ba937e876a3fdf":{
      "scriptId":"u0"},
    "d05fa9d0561c4a4c980b1f92c9b5d5b5":{
      "scriptId":"u1"},
    "61f267adb1ad4007b46036697a9d61e4":{
      "scriptId":"u2"},
    "5795d5f5468d4c05871fe1f756b82bee":{
      "scriptId":"u3"},
    "b1d67df57891432fbc34aa98d5cbd426":{
      "scriptId":"u4"},
    "86e16e18b64743afb42ba83cc1f9dca4":{
      "scriptId":"u5"},
    "2dc8939a5c6a4225883d9f8eab3a2924":{
      "scriptId":"u6"},
    "85f58c1de9c94178ac05a406a1c844c5":{
      "scriptId":"u7"},
    "27d13096f5f04a509fdecd65b9e26105":{
      "scriptId":"u8"},
    "a926b0072cce461c8772e3920a2dd0cf":{
      "scriptId":"u9"},
    "0583fa8eeb8d43028c597acd2e1ae0b1":{
      "scriptId":"u10"},
    "790e3ad163e84636884f496a4035b563":{
      "scriptId":"u11"},
    "8ea20c0407c648cfb83063c0f93c1a39":{
      "scriptId":"u12"},
    "1f3a42d1ce244665be6b34fe2c3d271b":{
      "scriptId":"u13"},
    "c04d5482b4944f3ebd0af0109c4a92bc":{
      "scriptId":"u14"},
    "4930e60651de4644aeeae681666c62c3":{
      "scriptId":"u15"},
    "403df68cf100469896aa92ec7006e812":{
      "scriptId":"u16"},
    "4ca7747593864230affefc2bd0399ac1":{
      "scriptId":"u17"},
    "9d2d674b04bf41a0a4fa1051ceebb975":{
      "scriptId":"u18"},
    "0972ec3f035b47edb378ce458e4a01e5":{
      "scriptId":"u19"},
    "eaa3f9d2cca5421aa865f193c8911f70":{
      "scriptId":"u20"},
    "52f78e6b9a2d46d59e273e69a15898d0":{
      "scriptId":"u21"},
    "0b0e42c804d642d29356fa937e51b899":{
      "scriptId":"u22"},
    "53f6c12e4c4c4b8a870a9d7a50e7bc23":{
      "scriptId":"u23"},
    "e932c758bf5f4ee2b8ca6c8b4e7b2af3":{
      "scriptId":"u24"},
    "2c91d95220414fbbacd93b84d8887697":{
      "scriptId":"u25"},
    "5fbe9bfed6ad4bdc81cbf8f28ca5879c":{
      "scriptId":"u26"},
    "2c2622437569472c86cde425f5469ff2":{
      "scriptId":"u27"},
    "9ce8f0dcf1e94678a335d80258d8de28":{
      "scriptId":"u28"},
    "4341297a00984eabae211ea0f4f44a62":{
      "scriptId":"u29"},
    "932023efdb364bb588be4a785c8b8abc":{
      "scriptId":"u30"},
    "2ce974e5ba5348bf9eaabdfd8f83f1fa":{
      "scriptId":"u31"},
    "a947eb4b26754d6f97045a7ba9678671":{
      "scriptId":"u32"},
    "a733ed0de79a4ca18ad2538427fa65df":{
      "scriptId":"u33"},
    "dcb1dbd8bd0f415a90a61b7aff5bbdec":{
      "scriptId":"u34"},
    "02ca2a9dc0e145158d393634a94ec887":{
      "scriptId":"u35"},
    "f91708ea1dbf418c808fe0e4ff408666":{
      "scriptId":"u36"},
    "0ad7226253a9466fae698e3bd91b5ccb":{
      "scriptId":"u37"},
    "1f70d488935245d9b321c2c14355df77":{
      "scriptId":"u38"},
    "5f7c748c3a8e4b09bd05e5bca26a3b25":{
      "scriptId":"u39"},
    "741999195b4a4d2da5eceb9f2dfa5a99":{
      "scriptId":"u40"},
    "52fc947b65664b56a576522d3e549cbc":{
      "scriptId":"u41"},
    "598e55cc2f854b568c1041e382f6548d":{
      "scriptId":"u42"},
    "e4dd3c8f7003420f959657a439f6fda8":{
      "scriptId":"u43"},
    "9a587a4fa2664e6f8968012a8226f371":{
      "scriptId":"u44"},
    "295b10b4b02c4cf6988bbf86de8cdc53":{
      "scriptId":"u45"},
    "bd436f9726324ae187888ef4959d7482":{
      "scriptId":"u46"},
    "0913dc1e9ff9405fbd839080075cde63":{
      "scriptId":"u47"},
    "80261bd5299440f58c22ce3f6856e004":{
      "scriptId":"u48"},
    "eb87f25265194476943871ec84cdeb9a":{
      "scriptId":"u49"},
    "5b8a6cc16ea64d05a317189353f51296":{
      "scriptId":"u50"},
    "3f1161d9bbe841a5872a4bdac2b8c851":{
      "scriptId":"u51"},
    "f8f9d270587f4232bb44586b77762d0d":{
      "scriptId":"u52"},
    "0962d79e6d244ac49a68e96733735795":{
      "scriptId":"u53"},
    "6a0203a44b004dca828fe34eb9499589":{
      "scriptId":"u54"},
    "6737965b82f044a887a0685afa0eb77e":{
      "scriptId":"u55"},
    "f9cce98eb79d4535bae134fb9ee2fe44":{
      "scriptId":"u56"},
    "a36e9ad4dcbd439fabafefcb17441930":{
      "scriptId":"u57"},
    "9f9b573fe3d54387a72dc3c5283d9a07":{
      "scriptId":"u58"},
    "9a33bb3572aa42e6a15171972703d324":{
      "scriptId":"u59"},
    "c68155f40dc548b0a1f16c0ea74e3fba":{
      "scriptId":"u60"},
    "62b1811a2e934f158c349ee1095d1786":{
      "scriptId":"u61"}}});