$axure.loadCurrentPage({
  "url":"登出.html",
  "generationDate":new Date(1528106885591.12),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"99ed77a957964d98bf8808d08d4a7828",
    "type":"Axure:Page",
    "name":"登出",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d6b8892d70c540f2b6591af2f84c23a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":160,
              "y":20},
            "size":{
              "width":650,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12a6d80c6df14d6fa1129ef76c7bfb56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":160,
                  "y":20},
                "size":{
                  "width":650,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登出/regen/u0.png"}},
{
          "id":"ebe9e1b606fe4d21a0a6441a356f26c0",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":370,
              "y":343},
            "size":{
              "width":100,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"c8785507e78b48f79292fa32d1dc7516",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":321,
              "y":208},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d3c56d22b4e4b498bb1e8a41ca337b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":321,
                  "y":208},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"830ee7d895c84d8b8cd853c57911158c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":321,
              "y":268},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd53a644c42047f0aa0d1fea7d387f10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":321,
                  "y":268},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee3f8d6f01464ded87234ac8957afbc4",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":306},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83e4d68c10e246058a17f017456290c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":306},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c4f248a648ad4d1fa81b939f3276afdd",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":306},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0dc369ef5834e87b4dc169a1a04df5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":306},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"7cd989f374dd438f9a093bbfaa0b16f7",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":362},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e09212248f2744b1a8237032f6620cb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":362},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"1bcfd622cd804f2ebe87e594e3aa9f61",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":208},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"de1fada53c354e1dae372626d62d3bf5",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":265},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8943944fa8e148ce8e2a3fe5b8cd935a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":140},
            "size":{
              "width":169,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fdc470e34544b769907203b6a1be5a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":140},
                "size":{
                  "width":169,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "d6b8892d70c540f2b6591af2f84c23a4":{
      "scriptId":"u0"},
    "12a6d80c6df14d6fa1129ef76c7bfb56":{
      "scriptId":"u1"},
    "ebe9e1b606fe4d21a0a6441a356f26c0":{
      "scriptId":"u2"},
    "c8785507e78b48f79292fa32d1dc7516":{
      "scriptId":"u3"},
    "8d3c56d22b4e4b498bb1e8a41ca337b4":{
      "scriptId":"u4"},
    "830ee7d895c84d8b8cd853c57911158c":{
      "scriptId":"u5"},
    "dd53a644c42047f0aa0d1fea7d387f10":{
      "scriptId":"u6"},
    "ee3f8d6f01464ded87234ac8957afbc4":{
      "scriptId":"u7"},
    "83e4d68c10e246058a17f017456290c9":{
      "scriptId":"u8"},
    "c4f248a648ad4d1fa81b939f3276afdd":{
      "scriptId":"u9"},
    "a0dc369ef5834e87b4dc169a1a04df5c":{
      "scriptId":"u10"},
    "7cd989f374dd438f9a093bbfaa0b16f7":{
      "scriptId":"u11"},
    "e09212248f2744b1a8237032f6620cb2":{
      "scriptId":"u12"},
    "1bcfd622cd804f2ebe87e594e3aa9f61":{
      "scriptId":"u13"},
    "de1fada53c354e1dae372626d62d3bf5":{
      "scriptId":"u14"},
    "8943944fa8e148ce8e2a3fe5b8cd935a":{
      "scriptId":"u15"},
    "4fdc470e34544b769907203b6a1be5a3":{
      "scriptId":"u16"}}});